////////////////////////////////////////////////
//References all the symbols that can be found//
//in the EXPORT sections of DAV & WAR files   //
////////////////////////////////////////////////

#ifndef __GameRes_h__
#define __GameRes_h__


#define WAR_IDO_ACAISS01               1
#define WAR_IDO_AETOIL01               2
#define WAR_IDO_AEXPLOS1               3
#define WAR_IDO_AEXPLOS2               4
#define WAR_IDO_ATESAM01               5
#define WAR_IDO_CAMCOLLBOX             6
#define WAR_IDO_CAMNOCOLLBOX           7
#define WAR_IDO_CINBBOX                8
#define WAR_IDO_CINSHEEPBBOX           9
#define WAR_IDO_DEATHBOX               10
#define DAV_IDI_I01LVU4_               11
#define DAV_IDI_I01LVU5_               12
#define DAV_IDI_IDCICONA               13
#define DAV_IDI_IDCICONB               14
#define DAV_IDI_IDYICONA               15
#define DAV_IDI_IDYICONB               16
#define DAV_IDI_IFUICONA               17
#define DAV_IDI_IFUICONB               18
#define DAV_IDI_IGLCADG_               19
#define DAV_IDI_IGLCADH_               20
#define DAV_IDI_IGLCADP_               21
#define DAV_IDI_IGLCERC_               22
#define DAV_IDI_IGLCOMBA               23
#define DAV_IDI_IGLCOMBB               24
#define DAV_IDI_IGLCRAI1               25
#define DAV_IDI_IGLEXITA               26
#define DAV_IDI_IGLEXITB               27
#define DAV_IDI_IGLFLEC_               28
#define DAV_IDI_IGLFONTE               29
#define DAV_IDI_IGLHELPA               30
#define DAV_IDI_IGLHELPB               31
#define DAV_IDI_IGLNEIG1               32
#define DAV_IDI_IGLOMBR1               33
#define DAV_IDI_IGLSMOK_               34
#define DAV_IDI_IGLTRIA_               35
#define DAV_IDI_IGLTYPO_               36
#define DAV_IDI_IGLUSEDA               37
#define DAV_IDI_IGLUSEDB               38
#define DAV_IDI_IGLVOL0_               39
#define DAV_IDI_IGLVOL1_               40
#define DAV_IDI_IGLVOL2_               41
#define DAV_IDI_IGLVOL3_               42
#define DAV_IDI_IGLVOL4_               43
#define DAV_IDI_ILAICONA               44
#define DAV_IDI_ILAICONB               45
#define DAV_IDI_IMEMCMAP               46
#define DAV_IDI_IMOICONA               47
#define DAV_IDI_IMOICONB               48
#define DAV_IDI_IVEICONA               49
#define DAV_IDI_IVEICONB               50
#define DAV_IDI_MAP                    51
#define WAR_IDO_SAMTRAJ                52
#define WAR_IDO_SHEEPREPELBOX          53
#define WAR_IDO_WATERBOX               54
#define DAV_IDI_IGLCRAI2               55
#define DAV_IDI_IENVMAP                56
#define DAV_IDI_IGLTIDE_               57
#define DAV_IDI_IFTICONA               58
#define DAV_IDI_IFTICONB               59
#define DAV_IDI_IFLICONA               60
#define DAV_IDI_IFLICONB               61
#define DAV_IDI_IGLBULL_               62
#define DAV_IDI_IFLFUMEE               63
#define WAR_IDO_ABCOYO01               64
#define DAV_IDI_IGAICONA               65
#define DAV_IDI_IGAICONB               66
#define DAV_IDI_IC4ICONA               67
#define DAV_IDI_IC4ICONB               68
#define WAR_IDO_BOXSAMGREEN            69
#define WAR_IDO_BOXSAMORANGE           70
#define DAV_IDI_ICTJAUG1               71
#define DAV_IDI_ICHICONB               72
#define WAR_IDO_ATEROB01               73
#define DAV_IDI_ICHICONA               74
#define DAV_IDI_IMNICONA               75
#define DAV_IDI_IMNICONB               76
#define DAV_IDI_IMNINT1_               77
#define DAV_IDI_IMNINT2_               78
#define DAV_IDI_IEAICONA               79
#define DAV_IDI_IEAICONB               80
#define DAV_IDI_IMNCERC_               81
#define WAR_IDO_AMOUTO03               82
#define DAV_IDI_IMNPADS_               83
#define DAV_IDI_IMNPADC_               84
#define DAV_IDI_IMNPADT_               85
#define DAV_IDI_IMNPADX_               86
#define DAV_IDI_IGLEAVE1               87
#define WAR_IDO_AROCHE5B               88
#define DAV_IDI_IMNINT3_               89
#define WAR_IDO_APLOUF01               90
#define DAV_IDI_IMNCHEK_               91
#define WAR_IDO_ICEBOX                 92
#define DAV_IDI_IAPICONA               93
#define DAV_IDI_IAPICONB               94
#define DAV_IDI_IFLOCO01               95
#define DAV_IDI_IAIICONA               96
#define DAV_IDI_IAIICONB               97
#define WAR_IDO_AGLACON1               98
#define WAR_IDO_AMCOYO01               99
#define WAR_IDO_AGLACON2               100
#define DAV_IDI_IDUICONB               101
#define DAV_IDI_IPRICONB               102
#define DAV_IDI_IPRICONA               103
#define WAR_IDO_SLIDEBOX               104
#define DAV_IDI_ICLICONA               105
#define DAV_IDI_ICLICONB               106
#define DAV_IDI_IDTICONA               107
#define DAV_IDI_IDTICONB               108
#define DAV_IDI_ICPICONA               109
#define DAV_IDI_ICPICONB               110
#define DAV_IDI_ICPICONC               111
#define DAV_IDI_IDTICONC               112
#define DAV_IDI_IDUICONA               113
#define DAV_IDI_IPMICONA               114
#define DAV_IDI_IPMICONB               115
#define WAR_IDO_AFEUIL01               116
#define DAV_IDI_IMGICONA               117
#define DAV_IDI_IMGICONB               118
#define WAR_IDO_ALAITU02               119
#define DAV_IDI_IFFICONA               120
#define DAV_IDI_IFFICONB               121
#define DAV_IDI_IPASNE01               122
#define WAR_IDO_PRINTSBOX              123
#define WAR_IDO_ACOLAP01               124
#define WAR_IDO_ABTIME02               125
#define DAV_IDI_ICFICONA               126
#define DAV_IDI_ICFICONB               127
#define WAR_IDO_ATELMER2               128
#define WAR_IDO_ABOULE01               129
#define DAV_IDI_ITICPTR_               130
#define DAV_IDI_IFUJAUG_               131
#define DAV_IDI_IFUJIC1_               132
#define DAV_IDI_IFUJIC2_               133
#define DAV_IDI_ITITRE01               134
#define DAV_IDI_ITITRE02               135
#define WAR_IDO_ACANON01               136
#define WAR_IDO_ACENSURE               137
#define DAV_IDI_ITRICONA               138
#define DAV_IDI_ITRICONB               139
#define DAV_IDI_ITITRE03               140
#define DAV_IDI_ITITRE04               141
#define DAV_IDI_IGLCOYO1               142
#define DAV_IDI_ISTART01               143
#define DAV_IDI_ISTART02               144
#define DAV_IDI_ISTART03               145
#define DAV_IDI_ISTART04               146
#define WAR_IDO_AGRILL01               147
#define WAR_IDO_AGRILL03               148
#define WAR_IDO_AGOOMB01               149
#define WAR_IDO_AGRILL02               150
#define WAR_IDO_ATAPIS01               151
#define DAV_IDI_ITPDESS_               152
#define WAR_IDO_GHOSTTRAJ              153
#define WAR_IDO_ACOGHO01               154
#define DAV_IDI_IASPILEA               155
#define DAV_IDI_IASPILEB               156
#define DAV_IDI_IASICONA               157
#define DAV_IDI_IASICONB               158
#define WAR_IDO_APIRANA1               159
#define DAV_IDI_ICSMASQ_               160
#define WAR_IDO_AGRILL04               161
#define DAV_IDI_ICPICOND               162
#define DAV_IDI_IORICONA               163
#define DAV_IDI_IORICONB               164
#define WAR_IDO_AFANTO03               165
#define WAR_IDO_ACAISS02               166
#define WAR_IDO_ALOCOM1A               167
#define WAR_IDO_ALOCOM1B               168
#define WAR_IDO_MARTIANEXCEPTINGBOX    169
#define WAR_IDO_ACAISS03               170
#define DAV_IDI_IGHICONA               171
#define DAV_IDI_IGHICONB               172
#define WAR_IDO_GRAVITYBOX             173
#define DAV_IDI_D0XCADR_               174
#define WAR_IDO_BEACHCSBOX1            175
#define WAR_IDO_BEACHCSBOX2            176
#define WAR_IDO_BEACHSAMIPOS2          177
#define WAR_IDO_AWAGON1A               178
#define WAR_IDO_AWAGON1B               179
#define WAR_IDO_AWAGON2A               180
#define WAR_IDO_AWAGON2B               181
#define WAR_IDO_AREDUC01               182
#define WAR_IDO_AREDUC03               183
#define WAR_IDO_APAPIL02               184
#define WAR_IDO_APAPIL03               185
#define WAR_IDO_ALAVE02                186
#define WAR_IDO_ALAVE03                187
#define WAR_IDO_ASABLE01               188
#define WAR_IDO_AFANTB02               189
#define WAR_IDO_AREDUC02               190
#define WAR_IDO_AFANTB01               191
#define WAR_IDO_AFANTO04               192
#define DAV_IDI_IGHICONC               193
#define DAV_IDI_IDTJAUG_               194
#define WAR_IDO_BEACHORANGEZONE2       195
#define WAR_IDO_BEACHGREENZONE2        196
#define WAR_IDO_SAMSPECIALBOX          197
#define WAR_IDO_AGRILL05               198
#define WAR_IDO_ASABLE02               199
#define WAR_IDO_BEACHPSBOX1            200
#define WAR_IDO_BEACHPSBOX2            201
#define WAR_IDO_SHADOWBOX              202
#define WAR_IDO_FALLINGGATE            203
#define WAR_IDO_FALLINGGATE2           204
#define WAR_IDO_WHEEL                  205
#define WAR_IDO_WOODENLIFT             206
#define DAV_IDI_IFAOREO_               207
#define DAV_IDI_IFBSMOK_               208
#define DAV_IDI_IFTNOTE_               209
#define DAV_IDI_IFTTSAM_               210
#define WAR_IDO_ACBOUE01               211
#define WAR_IDO_AGLACON3               212
#define WAR_IDO_ACROCO02               213
#define DAV_IDI_IMDANSE1               214
#define WAR_IDO_ACHRON01               215
#define WAR_IDO_ATIMER01               216
#define WAR_IDO_MINTDAN1               217
#define DAV_IDI_IMDANSE2               218
#define DAV_IDI_IMDANSE3               219
#define DAV_IDI_IMDANSE4               220
#define WAR_IDO_ATORCH02               221
#define WAR_IDO_AROCHE03               222
#define WAR_IDO_AEXPLOS3               223
#define WAR_IDO_AMINEM02               224
#define DAV_IDI_IGLGOUT1               225
#define WAR_IDO_ABOUTO01               226
#define WAR_IDO_AECLAI01               227
#define WAR_IDO_AMOUTO04               228
#define DAV_IDI_IBOCKOI_               229
#define DAV_IDI_IBOGAGN_               230
#define WAR_IDO_AROBIN01               231
#define DAV_IDI_IPASNE02               232
#define DAV_IDI_IGLGOUT2               233
#define WAR_IDO_CLIMATEBOX             234
#define DAV_IDI_IMEMCICA               235
#define DAV_IDI_IMEMCICB               236
#define DAV_IDI_IGLALFA_               237
#define DAV_IDI_IGLSMO2_               238
#define DAV_IDI_IGLLIGF_               239
#define DAV_IDI_IGLLIGB_               240


#endif
