////////////////////////////////////////////////
//References all the offsets of the properties//
//of the scenaric objects                     //
////////////////////////////////////////////////

#ifndef __Scenaric_Classes_h__
#define __Scenaric_Classes_h__


//////////////Definition of class "Wolf"
#define CLASSID_WOLF                      0

#define PROPERTY_WOLF_CLIMBBOXES          0
#define PROPERTY_WOLF_FLYBOX              4
#define PROPERTY_WOLF_RESTRICTIONBOX      8
#define PROPSIZE_WOLF                     12


//////////////Definition of class "Sam"
#define CLASSID_SAM                       1

#define PROPERTY_SAM_2NDCAMERABOX         0
#define PROPERTY_SAM_AUTHORIZEDZONE       4
#define PROPERTY_SAM_CATCHABLESHEEPBOX    8
#define PROPERTY_SAM_CIN01                12
#define PROPERTY_SAM_CIN01BOX             16
#define PROPERTY_SAM_CIN01FLAGS           20
#define PROPERTY_SAM_CIN01SHEEPBOX        24
#define PROPERTY_SAM_CIN01TEXT            28
#define PROPERTY_SAM_DEATHDURATIONMS      32
#define PROPERTY_SAM_DISTCATCH_PATROL     36
#define PROPERTY_SAM_DNTTRYTOCATCHSHPBOX  40
#define PROPERTY_SAM_GREENZONEBOX         44
#define PROPERTY_SAM_HEADSPEED            48
#define PROPERTY_SAM_HIDINGBOXES          52
#define PROPERTY_SAM_HYPNOTIZEDZONE       56
#define PROPERTY_SAM_MAXANGLE             60
#define PROPERTY_SAM_MODE                 64
#define PROPERTY_SAM_ORANGEZONEBOX        68
#define PROPERTY_SAM_PUTSHEEPBOX          72
#define PROPERTY_SAM_TRAJECTORY           76
#define PROPERTY_SAM_WATCHROBOTTIMEMS     80
#define PROPERTY_SAM_WOLFCANBEHITZONE     84
#define PROPSIZE_SAM                      88


//////////////Definition of class "Dynamite"
#define CLASSID_DYNAMITE                  2

#define PROPERTY_DYNAMITE_COUNTDOWN       0
#define PROPSIZE_DYNAMITE                 4


//////////////Definition of class "Salad"
#define CLASSID_SALAD                     3

#define PROPSIZE_SALAD                    0


//////////////Definition of class "Mailbox"
#define CLASSID_MAILBOX                   4

#define PROPERTY_MAILBOX_BOX1             0
#define PROPERTY_MAILBOX_BOX2             4
#define PROPERTY_MAILBOX_BOX3             8
#define PROPERTY_MAILBOX_BOX4             12
#define PROPERTY_MAILBOX_FLOATINGBOXES    16
#define PROPERTY_MAILBOX_IDCAMERA         20
#define PROPERTY_MAILBOX_LVL03ROCK        24
#define PROPERTY_MAILBOX_MAPPOSX          28
#define PROPERTY_MAILBOX_MAPPOSY          32
#define PROPERTY_MAILBOX_O1               36
#define PROPERTY_MAILBOX_O2               40
#define PROPERTY_MAILBOX_O3               44
#define PROPERTY_MAILBOX_O4               48
#define PROPERTY_MAILBOX_TIMERCAMERA      52
#define PROPSIZE_MAILBOX                  56


//////////////Definition of class "balance"
#define CLASSID_BALANCE                   5

#define PROPSIZE_BALANCE                  0


//////////////Definition of class "bridge"
#define CLASSID_BRIDGE                    6

#define PROPERTY_BRIDGE_FALLINGZONE       0
#define PROPERTY_BRIDGE_IDOBJECTSFALLZONE 4
#define PROPERTY_BRIDGE_OTHERPART         8
#define PROPSIZE_BRIDGE                   12


//////////////Definition of class "Fan"
#define CLASSID_FAN                       7

#define PROPSIZE_FAN                      0


//////////////Definition of class "robin"
#define CLASSID_ROBIN                     8

#define PROPSIZE_ROBIN                    0


//////////////Definition of class "Porky"
#define CLASSID_PORKY                     9

#define PROPSIZE_PORKY                    0


//////////////Definition of class "Rocket"
#define CLASSID_ROCKET                    10

#define PROPERTY_ROCKET_FUEL              0
#define PROPERTY_ROCKET_FUELCOLOR         4
#define PROPERTY_ROCKET_HITS              8
#define PROPERTY_ROCKET_HITSCOLOR         12
#define PROPSIZE_ROCKET                   16


//////////////Definition of class "Sheep"
#define CLASSID_SHEEP                     11

#define PROPERTY_SHEEP_SLEEPY             0
#define PROPSIZE_SHEEP                    4


//////////////Definition of class "MiscStatic"
#define CLASSID_MISCSTATIC                12

#define PROPSIZE_MISCSTATIC               0


//////////////Definition of class "Rocks"
#define CLASSID_ROCKS                     13

#define PROPSIZE_ROCKS                    0


//////////////Definition of class "box"
#define CLASSID_BOX                       14

#define PROPERTY_BOX_CONTAINS             0
#define PROPSIZE_BOX                      4


//////////////Definition of class "seesaw"
#define CLASSID_SEESAW                    15

#define PROPERTY_SEESAW_CAMERA1           0
#define PROPERTY_SEESAW_CAMERA1INTERPB    4
#define PROPERTY_SEESAW_CAMERA1INTERPE    8
#define PROPERTY_SEESAW_CAMERA2           12
#define PROPERTY_SEESAW_CAMERA2INTERPB    16
#define PROPERTY_SEESAW_CAMERA2INTERPE    20
#define PROPERTY_SEESAW_EJECTIONBOX1      24
#define PROPERTY_SEESAW_EJECTIONBOX2      28
#define PROPERTY_SEESAW_FLAGS             32
#define PROPERTY_SEESAW_MAXANGLE          36
#define PROPERTY_SEESAW_MAXANGLE2         40
#define PROPERTY_SEESAW_TRAJ1             44
#define PROPERTY_SEESAW_TRAJ2             48
#define PROPSIZE_SEESAW                   52


//////////////Definition of class "Rock"
#define CLASSID_ROCK                      16

#define PROPERTY_ROCK_ALLOWPUSHBOXES      0
#define PROPERTY_ROCK_ALLOWPUSHONXAXIS    4
#define PROPERTY_ROCK_ALLOWPUSHONYAXIS    8
#define PROPERTY_ROCK_FALLSATINIT         12
#define PROPERTY_ROCK_LVL03BOX            16
#define PROPERTY_ROCK_LVL03BOX01          20
#define PROPERTY_ROCK_LVL03BOX02          24
#define PROPERTY_ROCK_LVL03IDCAMERABOX    28
#define PROPERTY_ROCK_LVL03SEESAW         32
#define PROPERTY_ROCK_LVL03WITHBOX        36
#define PROPERTY_ROCK_LVL03WITHOUTBOX     40
#define PROPERTY_ROCK_RESET               44
#define PROPSIZE_ROCK                     48


//////////////Definition of class "Tree_02"
#define CLASSID_TREE_02                   17

#define PROPSIZE_TREE_02                  0


//////////////Definition of class "CameraManager"
#define CLASSID_CAMERAMANAGER             18

#define PROPERTY_CAMERAMANAGER_CAMERA01   0
#define PROPERTY_CAMERAMANAGER_CAMERA01BOX 4
#define PROPERTY_CAMERAMANAGER_CAMERA01INTB 8
#define PROPERTY_CAMERAMANAGER_CAMERA01INTE 12
#define PROPERTY_CAMERAMANAGER_CAMERA02   16
#define PROPERTY_CAMERAMANAGER_CAMERA02BOX 20
#define PROPERTY_CAMERAMANAGER_CAMERA02INTB 24
#define PROPERTY_CAMERAMANAGER_CAMERA02INTE 28
#define PROPERTY_CAMERAMANAGER_CAMERA03   32
#define PROPERTY_CAMERAMANAGER_CAMERA03BOX 36
#define PROPERTY_CAMERAMANAGER_CAMERA03INTB 40
#define PROPERTY_CAMERAMANAGER_CAMERA03INTE 44
#define PROPERTY_CAMERAMANAGER_CAMERA04   48
#define PROPERTY_CAMERAMANAGER_CAMERA04BOX 52
#define PROPERTY_CAMERAMANAGER_CAMERA04INTB 56
#define PROPERTY_CAMERAMANAGER_CAMERA04INTE 60
#define PROPERTY_CAMERAMANAGER_CAMERA05   64
#define PROPERTY_CAMERAMANAGER_CAMERA05BOX 68
#define PROPERTY_CAMERAMANAGER_CAMERA05INTB 72
#define PROPERTY_CAMERAMANAGER_CAMERA05INTE 76
#define PROPERTY_CAMERAMANAGER_CAMERA06   80
#define PROPERTY_CAMERAMANAGER_CAMERA06BOX 84
#define PROPERTY_CAMERAMANAGER_CAMERA06INTB 88
#define PROPERTY_CAMERAMANAGER_CAMERA06INTE 92
#define PROPERTY_CAMERAMANAGER_CAMERA07   96
#define PROPERTY_CAMERAMANAGER_CAMERA07BOX 100
#define PROPERTY_CAMERAMANAGER_CAMERA07INTB 104
#define PROPERTY_CAMERAMANAGER_CAMERA07INTE 108
#define PROPERTY_CAMERAMANAGER_CAMERA08   112
#define PROPERTY_CAMERAMANAGER_CAMERA08BOX 116
#define PROPERTY_CAMERAMANAGER_CAMERA08INTB 120
#define PROPERTY_CAMERAMANAGER_CAMERA08INTE 124
#define PROPERTY_CAMERAMANAGER_CAMERA09   128
#define PROPERTY_CAMERAMANAGER_CAMERA09BOX 132
#define PROPERTY_CAMERAMANAGER_CAMERA09INTB 136
#define PROPERTY_CAMERAMANAGER_CAMERA09INTE 140
#define PROPERTY_CAMERAMANAGER_CAMERA10   144
#define PROPERTY_CAMERAMANAGER_CAMERA10BOX 148
#define PROPERTY_CAMERAMANAGER_CAMERA10INTB 152
#define PROPERTY_CAMERAMANAGER_CAMERA10INTE 156
#define PROPERTY_CAMERAMANAGER_CAMERA11   160
#define PROPERTY_CAMERAMANAGER_CAMERA11BOX 164
#define PROPERTY_CAMERAMANAGER_CAMERA11INTB 168
#define PROPERTY_CAMERAMANAGER_CAMERA11INTE 172
#define PROPERTY_CAMERAMANAGER_CAMERA12   176
#define PROPERTY_CAMERAMANAGER_CAMERA12BOX 180
#define PROPERTY_CAMERAMANAGER_CAMERA12INTB 184
#define PROPERTY_CAMERAMANAGER_CAMERA12INTE 188
#define PROPERTY_CAMERAMANAGER_CAMERA13   192
#define PROPERTY_CAMERAMANAGER_CAMERA13BOX 196
#define PROPERTY_CAMERAMANAGER_CAMERA13INTB 200
#define PROPERTY_CAMERAMANAGER_CAMERA13INTE 204
#define PROPERTY_CAMERAMANAGER_CAMERA14   208
#define PROPERTY_CAMERAMANAGER_CAMERA14BOX 212
#define PROPERTY_CAMERAMANAGER_CAMERA14INTB 216
#define PROPERTY_CAMERAMANAGER_CAMERA14INTE 220
#define PROPERTY_CAMERAMANAGER_CAMERA15   224
#define PROPERTY_CAMERAMANAGER_CAMERA15BOX 228
#define PROPERTY_CAMERAMANAGER_CAMERA15INTB 232
#define PROPERTY_CAMERAMANAGER_CAMERA15INTE 236
#define PROPSIZE_CAMERAMANAGER            240


//////////////Definition of class "CameraRestriction"
#define CLASSID_CAMERARESTRICTION         19

#define PROPERTY_CAMERARESTRICTION_AIMCORRECTIONX 0
#define PROPERTY_CAMERARESTRICTION_AIMCORRECTIONY 4
#define PROPERTY_CAMERARESTRICTION_AIMCORRECTIONZ 8
#define PROPERTY_CAMERARESTRICTION_ALPHAMAX 12
#define PROPERTY_CAMERARESTRICTION_ALPHAMIN 16
#define PROPERTY_CAMERARESTRICTION_ALPHASPEED 20
#define PROPERTY_CAMERARESTRICTION_ALTITUDEMIN 24
#define PROPERTY_CAMERARESTRICTION_BETAMAX 28
#define PROPERTY_CAMERARESTRICTION_BETAMIN 32
#define PROPERTY_CAMERARESTRICTION_BETASPEED 36
#define PROPERTY_CAMERARESTRICTION_DISTMAX 40
#define PROPERTY_CAMERARESTRICTION_DISTMIN 44
#define PROPERTY_CAMERARESTRICTION_FOCAL  48
#define PROPERTY_CAMERARESTRICTION_FORBIDPADCONTROL 52
#define PROPERTY_CAMERARESTRICTION_GAMMAMAX 56
#define PROPERTY_CAMERARESTRICTION_GAMMAMIN 60
#define PROPERTY_CAMERARESTRICTION_GAMMASPEED 64
#define PROPERTY_CAMERARESTRICTION_INFLUENCEBOXES 68
#define PROPERTY_CAMERARESTRICTION_MIRRORBETAINTERVAL 72
#define PROPERTY_CAMERARESTRICTION_MISCFLAGS 76
#define PROPERTY_CAMERARESTRICTION_SNAPBETA 80
#define PROPERTY_CAMERARESTRICTION_TRAJECTORY 84
#define PROPSIZE_CAMERARESTRICTION        88


//////////////Definition of class "FallingRock"
#define CLASSID_FALLINGROCK               20

#define PROPERTY_FALLINGROCK_ACTIVATIONBOX 0
#define PROPERTY_FALLINGROCK_CAMERA       4
#define PROPERTY_FALLINGROCK_TIMERCAMERA  8
#define PROPSIZE_FALLINGROCK              12


//////////////Definition of class "SignPost"
#define CLASSID_SIGNPOST                  21

#define PROPERTY_SIGNPOST_DISTANCE        0
#define PROPERTY_SIGNPOST_ID_ANVIL        4
#define PROPERTY_SIGNPOST_ID_CAMERA       8
#define PROPERTY_SIGNPOST_TEXTNUM         12
#define PROPSIZE_SIGNPOST                 16


//////////////Definition of class "DaffyTrainingLevel"
#define CLASSID_DAFFYTRAININGLEVEL        22

#define PROPERTY_DAFFYTRAININGLEVEL_BOX_1 0
#define PROPERTY_DAFFYTRAININGLEVEL_BOX_2 4
#define PROPERTY_DAFFYTRAININGLEVEL_BOX_3 8
#define PROPERTY_DAFFYTRAININGLEVEL_BOX00 12
#define PROPERTY_DAFFYTRAININGLEVEL_BOX01 16
#define PROPERTY_DAFFYTRAININGLEVEL_BOX02 20
#define PROPERTY_DAFFYTRAININGLEVEL_BOX03 24
#define PROPERTY_DAFFYTRAININGLEVEL_BOX04 28
#define PROPERTY_DAFFYTRAININGLEVEL_BOX05 32
#define PROPERTY_DAFFYTRAININGLEVEL_BOX06 36
#define PROPERTY_DAFFYTRAININGLEVEL_BOX07 40
#define PROPERTY_DAFFYTRAININGLEVEL_BOX08 44
#define PROPERTY_DAFFYTRAININGLEVEL_BOX09 48
#define PROPERTY_DAFFYTRAININGLEVEL_BOX10 52
#define PROPERTY_DAFFYTRAININGLEVEL_BOX11 56
#define PROPERTY_DAFFYTRAININGLEVEL_BOX12 60
#define PROPERTY_DAFFYTRAININGLEVEL_BOX13 64
#define PROPERTY_DAFFYTRAININGLEVEL_BOX14 68
#define PROPERTY_DAFFYTRAININGLEVEL_BOX15 72
#define PROPERTY_DAFFYTRAININGLEVEL_BOX16 76
#define PROPERTY_DAFFYTRAININGLEVEL_CAMERAS 80
#define PROPERTY_DAFFYTRAININGLEVEL_CINEMATICS 84
#define PROPERTY_DAFFYTRAININGLEVEL_DAFFYHELPCAMS 88
#define PROPERTY_DAFFYTRAININGLEVEL_FROMPREVIOUS 92
#define PROPERTY_DAFFYTRAININGLEVEL_HELPBOX 96
#define PROPERTY_DAFFYTRAININGLEVEL_HELPTEXT 100
#define PROPERTY_DAFFYTRAININGLEVEL_HELPTRAJECTORIES 104
#define PROPERTY_DAFFYTRAININGLEVEL_HELPVOICE 108
#define PROPERTY_DAFFYTRAININGLEVEL_JOKEENABLED 112
#define PROPERTY_DAFFYTRAININGLEVEL_JOKEVOICE1 116
#define PROPERTY_DAFFYTRAININGLEVEL_JOKEVOICE2 120
#define PROPERTY_DAFFYTRAININGLEVEL_RACEBEGIN 124
#define PROPERTY_DAFFYTRAININGLEVEL_RACEEND 128
#define PROPERTY_DAFFYTRAININGLEVEL_RACETIME 132
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT_1 136
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT_2 140
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT_3 144
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT00 148
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT01 152
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT02 156
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT03 160
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT04 164
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT05 168
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT06 172
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT07 176
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT08 180
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT09 184
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT10 188
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT11 192
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT12 196
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT13 200
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT14 204
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT15 208
#define PROPERTY_DAFFYTRAININGLEVEL_TEXT16 212
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY_1 216
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY_2 220
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY_3 224
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY00 228
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY01 232
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY02 236
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY03 240
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY04 244
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY05 248
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY06 252
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY07 256
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY08 260
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY09 264
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY10 268
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY11 272
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY12 276
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY13 280
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY14 284
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY15 288
#define PROPERTY_DAFFYTRAININGLEVEL_TRAJECTORY16 292
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE_1 296
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE_2 300
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE_3 304
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE00 308
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE01 312
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE02 316
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE03 320
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE04 324
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE05 328
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE06 332
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE07 336
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE08 340
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE09 344
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE10 348
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE11 352
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE12 356
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE13 360
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE14 364
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE15 368
#define PROPERTY_DAFFYTRAININGLEVEL_TYPE16 372
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE_1 376
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE_2 380
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE_3 384
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE00 388
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE01 392
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE02 396
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE03 400
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE04 404
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE05 408
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE06 412
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE07 416
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE08 420
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE09 424
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE10 428
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE11 432
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE12 436
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE13 440
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE14 444
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE15 448
#define PROPERTY_DAFFYTRAININGLEVEL_VOICE16 452
#define PROPSIZE_DAFFYTRAININGLEVEL       456


//////////////Definition of class "Goal"
#define CLASSID_GOAL                      23

#define PROPERTY_GOAL_CINBOX              0
#define PROPERTY_GOAL_CINEMATIC           4
#define PROPERTY_GOAL_CINSHEEPBOX         8
#define PROPERTY_GOAL_FLAGS               12
#define PROPERTY_GOAL_FLAGSFORCIN         16
#define PROPERTY_GOAL_TEXTFORCIN          20
#define PROPSIZE_GOAL                     24


//////////////Definition of class "SensibleButton"
#define CLASSID_SENSIBLEBUTTON            24

#define PROPERTY_SENSIBLEBUTTON_TARGET    0
#define PROPERTY_SENSIBLEBUTTON_TARGET2   4
#define PROPERTY_SENSIBLEBUTTON_TYPE      8
#define PROPSIZE_SENSIBLEBUTTON           12


//////////////Definition of class "CheckpointManager"
#define CLASSID_CHECKPOINTMANAGER         25

#define PROPERTY_CHECKPOINTMANAGER_CHECK01_BOXES 0
#define PROPERTY_CHECKPOINTMANAGER_CHECK01_ORIENTATION 4
#define PROPERTY_CHECKPOINTMANAGER_CHECK01_SHEEP 8
#define PROPERTY_CHECKPOINTMANAGER_CHECK01_WOLF 12
#define PROPERTY_CHECKPOINTMANAGER_CHECK02_BOXES 16
#define PROPERTY_CHECKPOINTMANAGER_CHECK02_ORIENTATION 20
#define PROPERTY_CHECKPOINTMANAGER_CHECK02_SHEEP 24
#define PROPERTY_CHECKPOINTMANAGER_CHECK02_WOLF 28
#define PROPERTY_CHECKPOINTMANAGER_CHECK03_BOXES 32
#define PROPERTY_CHECKPOINTMANAGER_CHECK03_ORIENTATION 36
#define PROPERTY_CHECKPOINTMANAGER_CHECK03_SHEEP 40
#define PROPERTY_CHECKPOINTMANAGER_CHECK03_WOLF 44
#define PROPERTY_CHECKPOINTMANAGER_CHECK04_BOXES 48
#define PROPERTY_CHECKPOINTMANAGER_CHECK04_ORIENTATION 52
#define PROPERTY_CHECKPOINTMANAGER_CHECK04_SHEEP 56
#define PROPERTY_CHECKPOINTMANAGER_CHECK04_WOLF 60
#define PROPERTY_CHECKPOINTMANAGER_CHECK05_BOXES 64
#define PROPERTY_CHECKPOINTMANAGER_CHECK05_ORIENTATION 68
#define PROPERTY_CHECKPOINTMANAGER_CHECK05_SHEEP 72
#define PROPERTY_CHECKPOINTMANAGER_CHECK05_WOLF 76
#define PROPERTY_CHECKPOINTMANAGER_CHECK06_BOXES 80
#define PROPERTY_CHECKPOINTMANAGER_CHECK06_ORIENTATION 84
#define PROPERTY_CHECKPOINTMANAGER_CHECK06_SHEEP 88
#define PROPERTY_CHECKPOINTMANAGER_CHECK06_WOLF 92
#define PROPERTY_CHECKPOINTMANAGER_CHECK07_BOXES 96
#define PROPERTY_CHECKPOINTMANAGER_CHECK07_ORIENTATION 100
#define PROPERTY_CHECKPOINTMANAGER_CHECK07_SHEEP 104
#define PROPERTY_CHECKPOINTMANAGER_CHECK07_WOLF 108
#define PROPERTY_CHECKPOINTMANAGER_CHECK08_BOXES 112
#define PROPERTY_CHECKPOINTMANAGER_CHECK08_ORIENTATION 116
#define PROPERTY_CHECKPOINTMANAGER_CHECK08_SHEEP 120
#define PROPERTY_CHECKPOINTMANAGER_CHECK08_WOLF 124
#define PROPERTY_CHECKPOINTMANAGER_SHEEPANDWOLFONLY 128
#define PROPSIZE_CHECKPOINTMANAGER        132


//////////////Definition of class "FallingGate"
#define CLASSID_FALLINGGATE               26

#define PROPERTY_FALLINGGATE_CLOSED       0
#define PROPERTY_FALLINGGATE_CUTCAMERA    4
#define PROPERTY_FALLINGGATE_IDCAMERA     8
#define PROPERTY_FALLINGGATE_ONLYONEACTIVATION 12
#define PROPERTY_FALLINGGATE_TYPE         16
#define PROPSIZE_FALLINGGATE              20


//////////////Definition of class "Cactus"
#define CLASSID_CACTUS                    27

#define PROPSIZE_CACTUS                   0


//////////////Definition of class "Telescope"
#define CLASSID_TELESCOPE                 28

#define PROPERTY_TELESCOPE_CAMDISTNORMAL  0
#define PROPERTY_TELESCOPE_CAMDISTREVERSE 4
#define PROPERTY_TELESCOPE_INITHORANGLE   8
#define PROPERTY_TELESCOPE_INITVERTANGLE  12
#define PROPERTY_TELESCOPE_MAXHORANGLE    16
#define PROPERTY_TELESCOPE_MAXVERTANGLE   20
#define PROPERTY_TELESCOPE_NORMALBOXID    24
#define PROPERTY_TELESCOPE_NORMALFOCAL    28
#define PROPERTY_TELESCOPE_REVERSEBOXID   32
#define PROPERTY_TELESCOPE_REVERSEFOCAL   36
#define PROPSIZE_TELESCOPE                40


//////////////Definition of class "Anvil"
#define CLASSID_ANVIL                     29

#define PROPSIZE_ANVIL                    0


//////////////Definition of class "PorkyLevel01"
#define CLASSID_PORKYLEVEL01              30

#define PROPERTY_PORKYLEVEL01_ACTIVATIONBOX 0
#define PROPERTY_PORKYLEVEL01_ANSWERSTEXTS 4
#define PROPERTY_PORKYLEVEL01_ASKTEXT     8
#define PROPERTY_PORKYLEVEL01_CHOICESTEXTS 12
#define PROPERTY_PORKYLEVEL01_CINBOX      16
#define PROPERTY_PORKYLEVEL01_CINWITHOUTSHEEP 20
#define PROPERTY_PORKYLEVEL01_CINWITHOUTSHEEPTEXT 24
#define PROPERTY_PORKYLEVEL01_CINWITHSHEEP 28
#define PROPERTY_PORKYLEVEL01_CINWITHSHEEPTEXT 32
#define PROPERTY_PORKYLEVEL01_DISPLAYSALADMILLIS 36
#define PROPERTY_PORKYLEVEL01_SHEEPBOX    40
#define PROPERTY_PORKYLEVEL01_WITHOUTSHEEPTEXT2 44
#define PROPERTY_PORKYLEVEL01_WITHSHEEPTEXT2 48
#define PROPSIZE_PORKYLEVEL01             52


//////////////Definition of class "bipbip"
#define CLASSID_BIPBIP                    31

#define PROPERTY_BIPBIP_BOX_DECL          0
#define PROPERTY_BIPBIP_SPEED_ONE         4
#define PROPERTY_BIPBIP_SPEED_TWO         8
#define PROPERTY_BIPBIP_TRAJ_WALL         12
#define PROPERTY_BIPBIP_TRAJECTORY        16
#define PROPSIZE_BIPBIP                   20


//////////////Definition of class "CinematicsManager"
#define CLASSID_CINEMATICSMANAGER         32

#define PROPERTY_CINEMATICSMANAGER_CIN01  0
#define PROPERTY_CINEMATICSMANAGER_CIN01ACTBOX 4
#define PROPERTY_CINEMATICSMANAGER_CIN01BOX 8
#define PROPERTY_CINEMATICSMANAGER_CIN01FLAGS 12
#define PROPERTY_CINEMATICSMANAGER_CIN01SHEEPBOX 16
#define PROPERTY_CINEMATICSMANAGER_CIN01TEXT 20
#define PROPERTY_CINEMATICSMANAGER_CIN02  24
#define PROPERTY_CINEMATICSMANAGER_CIN02ACTBOX 28
#define PROPERTY_CINEMATICSMANAGER_CIN02BOX 32
#define PROPERTY_CINEMATICSMANAGER_CIN02FLAGS 36
#define PROPERTY_CINEMATICSMANAGER_CIN02SHEEPBOX 40
#define PROPERTY_CINEMATICSMANAGER_CIN02TEXT 44
#define PROPERTY_CINEMATICSMANAGER_CIN03  48
#define PROPERTY_CINEMATICSMANAGER_CIN03ACTBOX 52
#define PROPERTY_CINEMATICSMANAGER_CIN03BOX 56
#define PROPERTY_CINEMATICSMANAGER_CIN03FLAGS 60
#define PROPERTY_CINEMATICSMANAGER_CIN03SHEEPBOX 64
#define PROPERTY_CINEMATICSMANAGER_CIN03TEXT 68
#define PROPERTY_CINEMATICSMANAGER_CIN04  72
#define PROPERTY_CINEMATICSMANAGER_CIN04ACTBOX 76
#define PROPERTY_CINEMATICSMANAGER_CIN04BOX 80
#define PROPERTY_CINEMATICSMANAGER_CIN04FLAGS 84
#define PROPERTY_CINEMATICSMANAGER_CIN04SHEEPBOX 88
#define PROPERTY_CINEMATICSMANAGER_CIN04TEXT 92
#define PROPERTY_CINEMATICSMANAGER_CIN05  96
#define PROPERTY_CINEMATICSMANAGER_CIN05ACTBOX 100
#define PROPERTY_CINEMATICSMANAGER_CIN05BOX 104
#define PROPERTY_CINEMATICSMANAGER_CIN05FLAGS 108
#define PROPERTY_CINEMATICSMANAGER_CIN05SHEEPBOX 112
#define PROPERTY_CINEMATICSMANAGER_CIN05TEXT 116
#define PROPERTY_CINEMATICSMANAGER_CIN06  120
#define PROPERTY_CINEMATICSMANAGER_CIN06ACTBOX 124
#define PROPERTY_CINEMATICSMANAGER_CIN06BOX 128
#define PROPERTY_CINEMATICSMANAGER_CIN06FLAGS 132
#define PROPERTY_CINEMATICSMANAGER_CIN06SHEEPBOX 136
#define PROPERTY_CINEMATICSMANAGER_CIN06TEXT 140
#define PROPERTY_CINEMATICSMANAGER_CIN07  144
#define PROPERTY_CINEMATICSMANAGER_CIN07ACTBOX 148
#define PROPERTY_CINEMATICSMANAGER_CIN07BOX 152
#define PROPERTY_CINEMATICSMANAGER_CIN07FLAGS 156
#define PROPERTY_CINEMATICSMANAGER_CIN07SHEEPBOX 160
#define PROPERTY_CINEMATICSMANAGER_CIN07TEXT 164
#define PROPERTY_CINEMATICSMANAGER_CIN08  168
#define PROPERTY_CINEMATICSMANAGER_CIN08ACTBOX 172
#define PROPERTY_CINEMATICSMANAGER_CIN08BOX 176
#define PROPERTY_CINEMATICSMANAGER_CIN08FLAGS 180
#define PROPERTY_CINEMATICSMANAGER_CIN08SHEEPBOX 184
#define PROPERTY_CINEMATICSMANAGER_CIN08TEXT 188
#define PROPERTY_CINEMATICSMANAGER_CIN09  192
#define PROPERTY_CINEMATICSMANAGER_CIN09ACTBOX 196
#define PROPERTY_CINEMATICSMANAGER_CIN09BOX 200
#define PROPERTY_CINEMATICSMANAGER_CIN09FLAGS 204
#define PROPERTY_CINEMATICSMANAGER_CIN09SHEEPBOX 208
#define PROPERTY_CINEMATICSMANAGER_CIN09TEXT 212
#define PROPERTY_CINEMATICSMANAGER_CIN10  216
#define PROPERTY_CINEMATICSMANAGER_CIN10ACTBOX 220
#define PROPERTY_CINEMATICSMANAGER_CIN10BOX 224
#define PROPERTY_CINEMATICSMANAGER_CIN10FLAGS 228
#define PROPERTY_CINEMATICSMANAGER_CIN10SHEEPBOX 232
#define PROPERTY_CINEMATICSMANAGER_CIN10TEXT 236
#define PROPERTY_CINEMATICSMANAGER_CIN11  240
#define PROPERTY_CINEMATICSMANAGER_CIN11ACTBOX 244
#define PROPERTY_CINEMATICSMANAGER_CIN11BOX 248
#define PROPERTY_CINEMATICSMANAGER_CIN11FLAGS 252
#define PROPERTY_CINEMATICSMANAGER_CIN11SHEEPBOX 256
#define PROPERTY_CINEMATICSMANAGER_CIN11TEXT 260
#define PROPERTY_CINEMATICSMANAGER_CIN12  264
#define PROPERTY_CINEMATICSMANAGER_CIN12ACTBOX 268
#define PROPERTY_CINEMATICSMANAGER_CIN12BOX 272
#define PROPERTY_CINEMATICSMANAGER_CIN12FLAGS 276
#define PROPERTY_CINEMATICSMANAGER_CIN12SHEEPBOX 280
#define PROPERTY_CINEMATICSMANAGER_CIN12TEXT 284
#define PROPERTY_CINEMATICSMANAGER_CIN13  288
#define PROPERTY_CINEMATICSMANAGER_CIN13ACTBOX 292
#define PROPERTY_CINEMATICSMANAGER_CIN13BOX 296
#define PROPERTY_CINEMATICSMANAGER_CIN13FLAGS 300
#define PROPERTY_CINEMATICSMANAGER_CIN13SHEEPBOX 304
#define PROPERTY_CINEMATICSMANAGER_CIN13TEXT 308
#define PROPERTY_CINEMATICSMANAGER_CIN14  312
#define PROPERTY_CINEMATICSMANAGER_CIN14ACTBOX 316
#define PROPERTY_CINEMATICSMANAGER_CIN14BOX 320
#define PROPERTY_CINEMATICSMANAGER_CIN14FLAGS 324
#define PROPERTY_CINEMATICSMANAGER_CIN14SHEEPBOX 328
#define PROPERTY_CINEMATICSMANAGER_CIN14TEXT 332
#define PROPERTY_CINEMATICSMANAGER_CIN15  336
#define PROPERTY_CINEMATICSMANAGER_CIN15ACTBOX 340
#define PROPERTY_CINEMATICSMANAGER_CIN15BOX 344
#define PROPERTY_CINEMATICSMANAGER_CIN15FLAGS 348
#define PROPERTY_CINEMATICSMANAGER_CIN15SHEEPBOX 352
#define PROPERTY_CINEMATICSMANAGER_CIN15TEXT 356
#define PROPSIZE_CINEMATICSMANAGER        360


//////////////Definition of class "DaffyLevel01"
#define CLASSID_DAFFYLEVEL01              33

#define PROPERTY_DAFFYLEVEL01_ANSWERTEXTS 0
#define PROPERTY_DAFFYLEVEL01_CHOICETEXTS 4
#define PROPERTY_DAFFYLEVEL01_LEVEL       8
#define PROPERTY_DAFFYLEVEL01_NBCHOICES   12
#define PROPERTY_DAFFYLEVEL01_QUESTIONTEXT 16
#define PROPERTY_DAFFYLEVEL01_TEXTBURNT   20
#define PROPERTY_DAFFYLEVEL01_TEXTCAMERA  24
#define PROPERTY_DAFFYLEVEL01_VOICE1      28
#define PROPERTY_DAFFYLEVEL01_VOICE2      32
#define PROPERTY_DAFFYLEVEL01_VOICE3      36
#define PROPERTY_DAFFYLEVEL01_VOICE4      40
#define PROPERTY_DAFFYLEVEL01_VOICE5      44
#define PROPERTY_DAFFYLEVEL01_VOICEBURNT  48
#define PROPSIZE_DAFFYLEVEL01             52


//////////////Definition of class "TVSceneManager"
#define CLASSID_TVSCENEMANAGER            34

#define PROPERTY_TVSCENEMANAGER_CINE00    0
#define PROPERTY_TVSCENEMANAGER_CINE00FLAGS 4
#define PROPERTY_TVSCENEMANAGER_CINE00TEXT 8
#define PROPERTY_TVSCENEMANAGER_CINE01    12
#define PROPERTY_TVSCENEMANAGER_CINE01FLAGS 16
#define PROPERTY_TVSCENEMANAGER_CINE01TEXT 20
#define PROPERTY_TVSCENEMANAGER_CINE02    24
#define PROPERTY_TVSCENEMANAGER_CINE02FLAGS 28
#define PROPERTY_TVSCENEMANAGER_CINE02TEXT 32
#define PROPERTY_TVSCENEMANAGER_CINE03    36
#define PROPERTY_TVSCENEMANAGER_CINE03FLAGS 40
#define PROPERTY_TVSCENEMANAGER_CINE03TEXT 44
#define PROPERTY_TVSCENEMANAGER_CINE04    48
#define PROPERTY_TVSCENEMANAGER_CINE04FLAGS 52
#define PROPERTY_TVSCENEMANAGER_CINE04TEXT 56
#define PROPERTY_TVSCENEMANAGER_CINE05    60
#define PROPERTY_TVSCENEMANAGER_CINE05FLAGS 64
#define PROPERTY_TVSCENEMANAGER_CINE05TEXT 68
#define PROPERTY_TVSCENEMANAGER_CINE06    72
#define PROPERTY_TVSCENEMANAGER_CINE06FLAGS 76
#define PROPERTY_TVSCENEMANAGER_CINE06TEXT 80
#define PROPERTY_TVSCENEMANAGER_CINE07    84
#define PROPERTY_TVSCENEMANAGER_CINE07FLAGS 88
#define PROPERTY_TVSCENEMANAGER_CINE07TEXT 92
#define PROPERTY_TVSCENEMANAGER_CINE08    96
#define PROPERTY_TVSCENEMANAGER_CINE08FLAGS 100
#define PROPERTY_TVSCENEMANAGER_CINE08TEXT 104
#define PROPERTY_TVSCENEMANAGER_CINE09    108
#define PROPERTY_TVSCENEMANAGER_CINE09FLAGS 112
#define PROPERTY_TVSCENEMANAGER_CINE09TEXT 116
#define PROPERTY_TVSCENEMANAGER_CINE10    120
#define PROPERTY_TVSCENEMANAGER_CINE10FLAGS 124
#define PROPERTY_TVSCENEMANAGER_CINE10TEXT 128
#define PROPERTY_TVSCENEMANAGER_CINE11    132
#define PROPERTY_TVSCENEMANAGER_CINE11FLAGS 136
#define PROPERTY_TVSCENEMANAGER_CINE11TEXT 140
#define PROPERTY_TVSCENEMANAGER_CINE12    144
#define PROPERTY_TVSCENEMANAGER_CINE12FLAGS 148
#define PROPERTY_TVSCENEMANAGER_CINE12TEXT 152
#define PROPERTY_TVSCENEMANAGER_CINE13    156
#define PROPERTY_TVSCENEMANAGER_CINE13FLAGS 160
#define PROPERTY_TVSCENEMANAGER_CINE13TEXT 164
#define PROPERTY_TVSCENEMANAGER_CINE14    168
#define PROPERTY_TVSCENEMANAGER_CINE14FLAGS 172
#define PROPERTY_TVSCENEMANAGER_CINE14TEXT 176
#define PROPERTY_TVSCENEMANAGER_CINE15    180
#define PROPERTY_TVSCENEMANAGER_CINE15FLAGS 184
#define PROPERTY_TVSCENEMANAGER_CINE15TEXT 188
#define PROPERTY_TVSCENEMANAGER_CINE16    192
#define PROPERTY_TVSCENEMANAGER_CINE16FLAGS 196
#define PROPERTY_TVSCENEMANAGER_CINE16TEXT 200
#define PROPERTY_TVSCENEMANAGER_CINE17    204
#define PROPERTY_TVSCENEMANAGER_CINE17FLAGS 208
#define PROPERTY_TVSCENEMANAGER_CINE17TEXT 212
#define PROPERTY_TVSCENEMANAGER_CINE18    216
#define PROPERTY_TVSCENEMANAGER_CINE18FLAGS 220
#define PROPERTY_TVSCENEMANAGER_CINE18TEXT 224
#define PROPERTY_TVSCENEMANAGER_CINE19    228
#define PROPERTY_TVSCENEMANAGER_CINE19FLAGS 232
#define PROPERTY_TVSCENEMANAGER_CINE19TEXT 236
#define PROPERTY_TVSCENEMANAGER_CINE20    240
#define PROPERTY_TVSCENEMANAGER_CINE20FLAGS 244
#define PROPERTY_TVSCENEMANAGER_CINE20TEXT 248
#define PROPERTY_TVSCENEMANAGER_CINE21    252
#define PROPERTY_TVSCENEMANAGER_CINE21FLAGS 256
#define PROPERTY_TVSCENEMANAGER_CINE21TEXT 260
#define PROPERTY_TVSCENEMANAGER_CINEINTRO 264
#define PROPERTY_TVSCENEMANAGER_CINEINTROFLAGS 268
#define PROPERTY_TVSCENEMANAGER_CINEINTROTEXT 272
#define PROPERTY_TVSCENEMANAGER_EXEDEMO1  276
#define PROPERTY_TVSCENEMANAGER_EXEDEMO2  284
#define PROPERTY_TVSCENEMANAGER_EXELEV00  292
#define PROPERTY_TVSCENEMANAGER_EXELEV01  300
#define PROPERTY_TVSCENEMANAGER_EXELEV02  308
#define PROPERTY_TVSCENEMANAGER_EXELEV03  316
#define PROPERTY_TVSCENEMANAGER_EXELEV04  324
#define PROPERTY_TVSCENEMANAGER_EXELEV05  332
#define PROPERTY_TVSCENEMANAGER_EXELEV06  340
#define PROPERTY_TVSCENEMANAGER_EXELEV07  348
#define PROPERTY_TVSCENEMANAGER_EXELEV08  356
#define PROPERTY_TVSCENEMANAGER_EXELEV09  364
#define PROPERTY_TVSCENEMANAGER_EXELEV10  372
#define PROPERTY_TVSCENEMANAGER_EXELEV11  380
#define PROPERTY_TVSCENEMANAGER_EXELEV12  388
#define PROPERTY_TVSCENEMANAGER_EXELEV13  396
#define PROPERTY_TVSCENEMANAGER_EXELEV14  404
#define PROPERTY_TVSCENEMANAGER_EXELEV15  412
#define PROPERTY_TVSCENEMANAGER_EXELEV16  420
#define PROPERTY_TVSCENEMANAGER_EXELEV17  428
#define PROPERTY_TVSCENEMANAGER_EXELEV18  436
#define PROPERTY_TVSCENEMANAGER_EXELEV19  444
#define PROPERTY_TVSCENEMANAGER_EXELEV20  452
#define PROPERTY_TVSCENEMANAGER_EXELEV21  460
#define PROPERTY_TVSCENEMANAGER_EXELEV22  468
#define PROPERTY_TVSCENEMANAGER_GLOBALFLAGS 476
#define PROPSIZE_TVSCENEMANAGER           480


//////////////Definition of class "HiddenRocks"
#define CLASSID_HIDDENROCKS               35

#define PROPERTY_HIDDENROCKS_IDHIDDINGZONE 0
#define PROPSIZE_HIDDENROCKS              4


//////////////Definition of class "Wooden Lift"
#define CLASSID_WOODEN_LIFT               36

#define PROPERTY_WOODEN_LIFT_CAMERA       0
#define PROPERTY_WOODEN_LIFT_CAMERACHANGEZVALUE 4
#define PROPERTY_WOODEN_LIFT_IDCAMERABOX  8
#define PROPERTY_WOODEN_LIFT_MAXZVALUE    12
#define PROPERTY_WOODEN_LIFT_STEP         16
#define PROPSIZE_WOODEN_LIFT              20


//////////////Definition of class "GoldenRock"
#define CLASSID_GOLDENROCK                37

#define PROPERTY_GOLDENROCK_BOX           0
#define PROPERTY_GOLDENROCK_EARTH         4
#define PROPERTY_GOLDENROCK_FLAGEARTH     8
#define PROPERTY_GOLDENROCK_FLAGSPACE     12
#define PROPERTY_GOLDENROCK_SPACE         16
#define PROPSIZE_GOLDENROCK               20


//////////////Definition of class "TimeKeeper"
#define CLASSID_TIMEKEEPER                38

#define PROPSIZE_TIMEKEEPER               0


//////////////Definition of class "Perfume"
#define CLASSID_PERFUME                   39

#define PROPSIZE_PERFUME                  0


//////////////Definition of class "WoodenPlatForm"
#define CLASSID_WOODENPLATFORM            40

#define PROPERTY_WOODENPLATFORM_ACTIVATIONZONE 0
#define PROPERTY_WOODENPLATFORM_CAMERA    4
#define PROPERTY_WOODENPLATFORM_DOOR      8
#define PROPERTY_WOODENPLATFORM_IDMECHANISM 12
#define PROPERTY_WOODENPLATFORM_MINZVALUE 16
#define PROPERTY_WOODENPLATFORM_STEP      20
#define PROPSIZE_WOODENPLATFORM           24


//////////////Definition of class "Flute"
#define CLASSID_FLUTE                     41

#define PROPSIZE_FLUTE                    0


//////////////Definition of class "elastic"
#define CLASSID_ELASTIC                   42

#define PROPERTY_ELASTIC_DISTANCE_PROJECTION 0
#define PROPERTY_ELASTIC_HAUTEUR_PROJECTION 4
#define PROPERTY_ELASTIC_IDCAMERA         8
#define PROPERTY_ELASTIC_LONGUEUR_MAX     12
#define PROPERTY_ELASTIC_VITESSE_PROJECTION 16
#define PROPSIZE_ELASTIC                  20


//////////////Definition of class "bull"
#define CLASSID_BULL                      43

#define PROPERTY_BULL_ACTIVATIONBOX       0
#define PROPERTY_BULL_ASLEEP              4
#define PROPERTY_BULL_MOVEMENTBOX         8
#define PROPERTY_BULL_NORETURNBOX         12
#define PROPERTY_BULL_REDOBJECTS          16
#define PROPERTY_BULL_SHEEPBOX            20
#define PROPERTY_BULL_SHEEPCAM            24
#define PROPERTY_BULL_SHEEPTRAJ           28
#define PROPERTY_BULL_WAKEUPSPEED         32
#define PROPSIZE_BULL                     36


//////////////Definition of class "SecretDoor"
#define CLASSID_SECRETDOOR                44

#define PROPSIZE_SECRETDOOR               0


//////////////Definition of class "ElasticTree"
#define CLASSID_ELASTICTREE               45

#define PROPERTY_ELASTICTREE_IDCAMREST    0
#define PROPERTY_ELASTICTREE_IDPOINTUP    4
#define PROPSIZE_ELASTICTREE              8


//////////////Definition of class "ElasticHook"
#define CLASSID_ELASTICHOOK               46

#define PROPSIZE_ELASTICHOOK              0


//////////////Definition of class "DaffyLevel02"
#define CLASSID_DAFFYLEVEL02              47

#define PROPERTY_DAFFYLEVEL02_ACTIVATIONBOX 0
#define PROPERTY_DAFFYLEVEL02_CINE        4
#define PROPERTY_DAFFYLEVEL02_CINE2       8
#define PROPERTY_DAFFYLEVEL02_CINEBOX     12
#define PROPERTY_DAFFYLEVEL02_CINEFLAGS   16
#define PROPERTY_DAFFYLEVEL02_CINESHEEPBOX 20
#define PROPERTY_DAFFYLEVEL02_CINETEXT    24
#define PROPERTY_DAFFYLEVEL02_GOALBOX     28
#define PROPERTY_DAFFYLEVEL02_STARTBOX    32
#define PROPERTY_DAFFYLEVEL02_TEXTBURNT   36
#define PROPSIZE_DAFFYLEVEL02             40


//////////////Definition of class "Bush"
#define CLASSID_BUSH                      48

#define PROPSIZE_BUSH                     0


//////////////Definition of class "RedThing"
#define CLASSID_REDTHING                  49

#define PROPSIZE_REDTHING                 0


//////////////Definition of class "Shark"
#define CLASSID_SHARK                     50

#define PROPERTY_SHARK_BOOLWATCHOVERCAVE  0
#define PROPERTY_SHARK_BOX                4
#define PROPERTY_SHARK_DETECTHEIGHT       8
#define PROPERTY_SHARK_DETECTRANGE        12
#define PROPERTY_SHARK_TRAJ               16
#define PROPSIZE_SHARK                    20


//////////////Definition of class "RedScarf"
#define CLASSID_REDSCARF                  51

#define PROPSIZE_REDSCARF                 0


//////////////Definition of class "TriggedStone"
#define CLASSID_TRIGGEDSTONE              52

#define PROPERTY_TRIGGEDSTONE_CRASHINGZONE 0
#define PROPERTY_TRIGGEDSTONE_IDCAMERA    4
#define PROPERTY_TRIGGEDSTONE_TIMER       8
#define PROPSIZE_TRIGGEDSTONE             12


//////////////Definition of class "Raft"
#define CLASSID_RAFT                      53

#define PROPERTY_RAFT_RESET               0
#define PROPSIZE_RAFT                     4


//////////////Definition of class "HeapOfLeaf"
#define CLASSID_HEAPOFLEAF                54

#define PROPERTY_HEAPOFLEAF_GLOBALZONE    0
#define PROPERTY_HEAPOFLEAF_IDGUARDIAN    4
#define PROPERTY_HEAPOFLEAF_IDPOLY        8
#define PROPSIZE_HEAPOFLEAF               12


//////////////Definition of class "DaffyElf"
#define CLASSID_DAFFYELF                  55

#define PROPERTY_DAFFYELF_ANSWERNUMBER    0
#define PROPERTY_DAFFYELF_ANSWERTEXTINDEX 4
#define PROPERTY_DAFFYELF_CINE            8
#define PROPERTY_DAFFYELF_CINEBOX         12
#define PROPERTY_DAFFYELF_CINEFLAGS       16
#define PROPERTY_DAFFYELF_CINESHEEPBOX    20
#define PROPERTY_DAFFYELF_CINETEXT        24
#define PROPERTY_DAFFYELF_IDFLUTE         28
#define PROPSIZE_DAFFYELF                 32


//////////////Definition of class "Catapult"
#define CLASSID_CATAPULT                  56

#define PROPERTY_CATAPULT_ACTIVATIONBOX   0
#define PROPERTY_CATAPULT_ARMLENGTH1      4
#define PROPERTY_CATAPULT_ARMLENGTH2      8
#define PROPERTY_CATAPULT_ARMLENGTH3      12
#define PROPERTY_CATAPULT_H0              16
#define PROPERTY_CATAPULT_MAXDIST         20
#define PROPERTY_CATAPULT_MOBILECAMERA    24
#define PROPERTY_CATAPULT_MOBILECAMERADIST 28
#define PROPERTY_CATAPULT_OFFSET0         32
#define PROPERTY_CATAPULT_TRAJECTORY      36
#define PROPSIZE_CATAPULT                 40


//////////////Definition of class "DaffyMilitary"
#define CLASSID_DAFFYMILITARY             57

#define PROPERTY_DAFFYMILITARY_CINE       0
#define PROPERTY_DAFFYMILITARY_CINETXT    4
#define PROPERTY_DAFFYMILITARY_FLAGCINE   8
#define PROPERTY_DAFFYMILITARY_PUNISHTEXT 12
#define PROPERTY_DAFFYMILITARY_TALKABOUTNBCHOICE 16
#define PROPERTY_DAFFYMILITARY_TALKABOUTTXT 20
#define PROPSIZE_DAFFYMILITARY            24


//////////////Definition of class "HairDryer"
#define CLASSID_HAIRDRYER                 58

#define PROPSIZE_HAIRDRYER                0


//////////////Definition of class "DoorMechanism"
#define CLASSID_DOORMECHANISM             59

#define PROPSIZE_DOORMECHANISM            0


//////////////Definition of class "IceCube"
#define CLASSID_ICECUBE                   60

#define PROPERTY_ICECUBE_OBJ              0
#define PROPSIZE_ICECUBE                  4


//////////////Definition of class "MineDetector"
#define CLASSID_MINEDETECTOR              61

#define PROPSIZE_MINEDETECTOR             0


//////////////Definition of class "Umbrella"
#define CLASSID_UMBRELLA                  62

#define PROPSIZE_UMBRELLA                 0


//////////////Definition of class "Stump"
#define CLASSID_STUMP                     63

#define PROPSIZE_STUMP                    0


//////////////Definition of class "DefusableMine"
#define CLASSID_DEFUSABLEMINE             64

#define PROPERTY_DEFUSABLEMINE_CODE       0
#define PROPERTY_DEFUSABLEMINE_CODEINIT   4
#define PROPERTY_DEFUSABLEMINE_CODELENGTH 8
#define PROPERTY_DEFUSABLEMINE_CODESPEED  12
#define PROPSIZE_DEFUSABLEMINE            16


//////////////Definition of class "SmallRock"
#define CLASSID_SMALLROCK                 65

#define PROPERTY_SMALLROCK_FALLSATINIT    0
#define PROPERTY_SMALLROCK_INITATRESET    4
#define PROPERTY_SMALLROCK_SLIDINGBOX     8
#define PROPSIZE_SMALLROCK                12


//////////////Definition of class "Magnet"
#define CLASSID_MAGNET                    66

#define PROPSIZE_MAGNET                   0


//////////////Definition of class "FishingRod"
#define CLASSID_FISHINGROD                67

#define PROPSIZE_FISHINGROD               0


//////////////Definition of class "MagnetRod"
#define CLASSID_MAGNETROD                 68

#define PROPSIZE_MAGNETROD                0


//////////////Definition of class "Seaweed"
#define CLASSID_SEAWEED                   69

#define PROPSIZE_SEAWEED                  0


//////////////Definition of class "VisibilityManager"
#define CLASSID_VISIBILITYMANAGER         70

#define PROPERTY_VISIBILITYMANAGER_CANTSEE1 0
#define PROPERTY_VISIBILITYMANAGER_CANTSEE2 4
#define PROPERTY_VISIBILITYMANAGER_CANTSEE3 8
#define PROPERTY_VISIBILITYMANAGER_WHENINBOX 12
#define PROPERTY_VISIBILITYMANAGER_WHENINBOX2 16
#define PROPERTY_VISIBILITYMANAGER_WHENINBOX3 20
#define PROPERTY_VISIBILITYMANAGER_WHENINBOX4 24
#define PROPSIZE_VISIBILITYMANAGER        28


//////////////Definition of class "HitSwitch"
#define CLASSID_HITSWITCH                 71

#define PROPERTY_HITSWITCH_TARGETS        0
#define PROPSIZE_HITSWITCH                4


//////////////Definition of class "GeyserIn"
#define CLASSID_GEYSERIN                  72

#define PROPERTY_GEYSERIN_ALWAYSMANAGE    0
#define PROPERTY_GEYSERIN_BOXDETECT       4
#define PROPERTY_GEYSERIN_CAMERA          8
#define PROPERTY_GEYSERIN_PERIODINSEC     12
#define PROPERTY_GEYSERIN_SLAVE           16
#define PROPERTY_GEYSERIN_TARGET          20
#define PROPERTY_GEYSERIN_TIMEENDOFCORK   24
#define PROPERTY_GEYSERIN_TIMEINPIPEINSEC 28
#define PROPERTY_GEYSERIN_TIMETOINHALE    32
#define PROPSIZE_GEYSERIN                 36


//////////////Definition of class "GeyserOut"
#define CLASSID_GEYSEROUT                 73

#define PROPERTY_GEYSEROUT_ALWAYSSPIT     0
#define PROPERTY_GEYSEROUT_CAMERA         4
#define PROPERTY_GEYSEROUT_CAMERAFORSALAD 8
#define PROPERTY_GEYSEROUT_CAMINTERPOLATE 12
#define PROPERTY_GEYSEROUT_SPITBOX        16
#define PROPERTY_GEYSEROUT_TRAJECTORY     20
#define PROPERTY_GEYSEROUT_TRAJECTORYWOLF 24
#define PROPSIZE_GEYSEROUT                28


//////////////Definition of class "FogManager"
#define CLASSID_FOGMANAGER                74

#define PROPERTY_FOGMANAGER_AUTOCLEAR     0
#define PROPERTY_FOGMANAGER_FOG2_COLOR    4
#define PROPERTY_FOGMANAGER_GRUGRU_COLOR  8
#define PROPERTY_FOGMANAGER_MAX           12
#define PROPERTY_FOGMANAGER_MIN           16
#define PROPERTY_FOGMANAGER_PAUSE_COLOR   20
#define PROPERTY_FOGMANAGER_WATER_COLOR   24
#define PROPSIZE_FOGMANAGER               28


//////////////Definition of class "Snowball"
#define CLASSID_SNOWBALL                  75

#define PROPERTY_SNOWBALL_ZONE            0
#define PROPSIZE_SNOWBALL                 4


//////////////Definition of class "SnowyGround"
#define CLASSID_SNOWYGROUND               76

#define PROPSIZE_SNOWYGROUND              0


//////////////Definition of class "IceGround"
#define CLASSID_ICEGROUND                 77

#define PROPERTY_ICEGROUND_IDCAMERA       0
#define PROPSIZE_ICEGROUND                4


//////////////Definition of class "SignPostSimple"
#define CLASSID_SIGNPOSTSIMPLE            78

#define PROPERTY_SIGNPOSTSIMPLE_DISTANCE  0
#define PROPERTY_SIGNPOSTSIMPLE_HIDDEN    4
#define PROPERTY_SIGNPOSTSIMPLE_INDEXTEXT 8
#define PROPSIZE_SIGNPOSTSIMPLE           12


//////////////Definition of class "SlidingIceCube"
#define CLASSID_SLIDINGICECUBE            79

#define PROPERTY_SLIDINGICECUBE_ALLOWPUSHBOXES 0
#define PROPERTY_SLIDINGICECUBE_ALLOWPUSHONXAXIS 4
#define PROPERTY_SLIDINGICECUBE_ALLOWPUSHONYAXIS 8
#define PROPSIZE_SLIDINGICECUBE           12


//////////////Definition of class "SheepCostume"
#define CLASSID_SHEEPCOSTUME              80

#define PROPSIZE_SHEEPCOSTUME             0


//////////////Definition of class "WolfTrap"
#define CLASSID_WOLFTRAP                  81

#define PROPSIZE_WOLFTRAP                 0


//////////////Definition of class "Crane"
#define CLASSID_CRANE                     82

#define PROPERTY_CRANE_ACTIVATIONBOX      0
#define PROPERTY_CRANE_CAMERA             4
#define PROPERTY_CRANE_CINE               8
#define PROPERTY_CRANE_CINEBOX            12
#define PROPERTY_CRANE_CINEFLAG           16
#define PROPERTY_CRANE_CINESHEEPBOX       20
#define PROPERTY_CRANE_CINETEXT           24
#define PROPSIZE_CRANE                    28


//////////////Definition of class "FrozenRiver"
#define CLASSID_FROZENRIVER               83

#define PROPERTY_FROZENRIVER_CAMERA       0
#define PROPERTY_FROZENRIVER_IDWATERBOX   4
#define PROPERTY_FROZENRIVER_IDWATERTRAJ  8
#define PROPSIZE_FROZENRIVER              12


//////////////Definition of class "Dragon"
#define CLASSID_DRAGON                    84

#define PROPERTY_DRAGON_BOXFIRSTCONTACT   0
#define PROPERTY_DRAGON_BOXFLY1           4
#define PROPERTY_DRAGON_BOXFLY2           8
#define PROPERTY_DRAGON_BOXFLY3           12
#define PROPERTY_DRAGON_BOXFLY4           16
#define PROPERTY_DRAGON_BOXFLY5           20
#define PROPERTY_DRAGON_CINECHRONOBALL    24
#define PROPERTY_DRAGON_CINEFIRSTCONTACT  28
#define PROPERTY_DRAGON_FLAGCHRONOBALL    32
#define PROPERTY_DRAGON_FLAGFIRSTCONTACT  36
#define PROPERTY_DRAGON_ROCKZONE          40
#define PROPERTY_DRAGON_ZONE              44
#define PROPSIZE_DRAGON                   48


//////////////Definition of class "TimeMachineChrono"
#define CLASSID_TIMEMACHINECHRONO         85

#define PROPSIZE_TIMEMACHINECHRONO        0


//////////////Definition of class "TimeMachineSphere"
#define CLASSID_TIMEMACHINESPHERE         86

#define PROPERTY_TIMEMACHINESPHERE_BOXPAST 0
#define PROPERTY_TIMEMACHINESPHERE_BOXPRESENT 4
#define PROPERTY_TIMEMACHINESPHERE_OBJECT00PAST 8
#define PROPERTY_TIMEMACHINESPHERE_OBJECT00PRESENT 12
#define PROPERTY_TIMEMACHINESPHERE_OBJECT01PAST 16
#define PROPERTY_TIMEMACHINESPHERE_OBJECT01PRESENT 20
#define PROPERTY_TIMEMACHINESPHERE_OBJECT02PAST 24
#define PROPERTY_TIMEMACHINESPHERE_OBJECT02PRESENT 28
#define PROPERTY_TIMEMACHINESPHERE_OBJECT03PAST 32
#define PROPERTY_TIMEMACHINESPHERE_OBJECT03PRESENT 36
#define PROPERTY_TIMEMACHINESPHERE_OBJECT04PAST 40
#define PROPERTY_TIMEMACHINESPHERE_OBJECT04PRESENT 44
#define PROPERTY_TIMEMACHINESPHERE_OBJECT05PAST 48
#define PROPERTY_TIMEMACHINESPHERE_OBJECT05PRESENT 52
#define PROPERTY_TIMEMACHINESPHERE_OBJECT06PAST 56
#define PROPERTY_TIMEMACHINESPHERE_OBJECT06PRESENT 60
#define PROPERTY_TIMEMACHINESPHERE_OBJECT07PAST 64
#define PROPERTY_TIMEMACHINESPHERE_OBJECT07PRESENT 68
#define PROPERTY_TIMEMACHINESPHERE_OBJECT08PAST 72
#define PROPERTY_TIMEMACHINESPHERE_OBJECT08PRESENT 76
#define PROPERTY_TIMEMACHINESPHERE_OBJECT09PAST 80
#define PROPERTY_TIMEMACHINESPHERE_OBJECT09PRESENT 84
#define PROPERTY_TIMEMACHINESPHERE_OBJECT10PAST 88
#define PROPERTY_TIMEMACHINESPHERE_OBJECT10PRESENT 92
#define PROPERTY_TIMEMACHINESPHERE_OBJECT11PAST 96
#define PROPERTY_TIMEMACHINESPHERE_OBJECT11PRESENT 100
#define PROPERTY_TIMEMACHINESPHERE_OBJECT12PAST 104
#define PROPERTY_TIMEMACHINESPHERE_OBJECT12PRESENT 108
#define PROPERTY_TIMEMACHINESPHERE_OBJECT13PAST 112
#define PROPERTY_TIMEMACHINESPHERE_OBJECT13PRESENT 116
#define PROPERTY_TIMEMACHINESPHERE_OBJECT14PAST 120
#define PROPERTY_TIMEMACHINESPHERE_OBJECT14PRESENT 124
#define PROPERTY_TIMEMACHINESPHERE_OBJECT15PAST 128
#define PROPERTY_TIMEMACHINESPHERE_OBJECT15PRESENT 132
#define PROPSIZE_TIMEMACHINESPHERE        136


//////////////Definition of class "Gossamer_Lev08"
#define CLASSID_GOSSAMER_LEV08            87

#define PROPERTY_GOSSAMER_LEV08_CINEFLAGS 0
#define PROPERTY_GOSSAMER_LEV08_CINEFLAGS2 4
#define PROPERTY_GOSSAMER_LEV08_CINETEXT  8
#define PROPERTY_GOSSAMER_LEV08_CINETEXT2 12
#define PROPERTY_GOSSAMER_LEV08_IDBULL    16
#define PROPERTY_GOSSAMER_LEV08_IDCINEBOX 20
#define PROPERTY_GOSSAMER_LEV08_IDCINEBOX2 24
#define PROPERTY_GOSSAMER_LEV08_IDCINEMATIC 28
#define PROPERTY_GOSSAMER_LEV08_IDCINEMATIC2 32
#define PROPERTY_GOSSAMER_LEV08_IDFLEEINGTRAJ 36
#define PROPERTY_GOSSAMER_LEV08_IDFUTURACTIONZONE 40
#define PROPERTY_GOSSAMER_LEV08_IDFUTURACTIONZONE2 44
#define PROPERTY_GOSSAMER_LEV08_IDFUTURACTIONZONE3 48
#define PROPERTY_GOSSAMER_LEV08_IDPASTACTIONZONE 52
#define PROPSIZE_GOSSAMER_LEV08           56


//////////////Definition of class "GroundMine"
#define CLASSID_GROUNDMINE                88

#define PROPERTY_GROUNDMINE_BOXES         0
#define PROPERTY_GROUNDMINE_RADIUS        4
#define PROPERTY_GROUNDMINE_TIMEINS       8
#define PROPERTY_GROUNDMINE_TRAJECTORIES  12
#define PROPSIZE_GROUNDMINE               16


//////////////Definition of class "SwirlSign"
#define CLASSID_SWIRLSIGN                 89

#define PROPERTY_SWIRLSIGN_ISRABBIT       0
#define PROPSIZE_SWIRLSIGN                4


//////////////Definition of class "Elmer"
#define CLASSID_ELMER                     90

#define PROPERTY_ELMER_BULLET             0
#define PROPERTY_ELMER_CAMERA             4
#define PROPERTY_ELMER_DAFFYTEXT          8
#define PROPERTY_ELMER_DETECTBOX          12
#define PROPERTY_ELMER_EXCEPTMOVINGBOX    16
#define PROPERTY_ELMER_MOVINGBOX          20
#define PROPERTY_ELMER_RABBITTEXT         24
#define PROPERTY_ELMER_SWIRLSIGN          28
#define PROPERTY_ELMER_TRAJECTORY         32
#define PROPERTY_ELMER_TREESECTION        36
#define PROPSIZE_ELMER                    40


//////////////Definition of class "TreeSection"
#define CLASSID_TREESECTION               91

#define PROPSIZE_TREESECTION              0


//////////////Definition of class "Bullet"
#define CLASSID_BULLET                    92

#define PROPSIZE_BULLET                   0


//////////////Definition of class "Seed"
#define CLASSID_SEED                      93

#define PROPERTY_SEED_BOXES               0
#define PROPERTY_SEED_TREE                4
#define PROPSIZE_SEED                     8


//////////////Definition of class "Tree"
#define CLASSID_TREE                      94

#define PROPERTY_TREE_VISIBLEDIRECTLY     0
#define PROPSIZE_TREE                     4


//////////////Definition of class "CannonBall"
#define CLASSID_CANNONBALL                95

#define PROPERTY_CANNONBALL_LIFETIME      0
#define PROPERTY_CANNONBALL_PARABOLIC     4
#define PROPERTY_CANNONBALL_WEIGHT        8
#define PROPSIZE_CANNONBALL               12


//////////////Definition of class "Pipe"
#define CLASSID_PIPE                      96

#define PROPERTY_PIPE_BOXACTI1            0
#define PROPERTY_PIPE_BOXACTI2            4
#define PROPERTY_PIPE_BOXLOCKUP           8
#define PROPERTY_PIPE_FORBID_IN_X         12
#define PROPERTY_PIPE_FORBID_IN_Z         16
#define PROPSIZE_PIPE                     20


//////////////Definition of class "CanonSimple"
#define CLASSID_CANONSIMPLE               97

#define PROPERTY_CANONSIMPLE__ACTIVATIONBOX 0
#define PROPERTY_CANONSIMPLE_ANGLEX       4
#define PROPERTY_CANONSIMPLE_ANGLEY       8
#define PROPERTY_CANONSIMPLE_CANNONBALL   12
#define PROPERTY_CANONSIMPLE_CANONDUMMY   16
#define PROPERTY_CANONSIMPLE_HORZLIMIT    20
#define PROPERTY_CANONSIMPLE_VERTLIMIT    24
#define PROPSIZE_CANONSIMPLE              28


//////////////Definition of class "MCardManager"
#define CLASSID_MCARDMANAGER              98

#define PROPERTY_MCARDMANAGER_ID_CAMERA   0
#define PROPSIZE_MCARDMANAGER             4


//////////////Definition of class "RabbitCostume"
#define CLASSID_RABBITCOSTUME             99

#define PROPSIZE_RABBITCOSTUME            0


//////////////Definition of class "RemoteControl"
#define CLASSID_REMOTECONTROL             100

#define PROPERTY_REMOTECONTROL_SWITCHONOFF 0
#define PROPERTY_REMOTECONTROL_TARGET     4
#define PROPSIZE_REMOTECONTROL            8


//////////////Definition of class "Robot"
#define CLASSID_ROBOT                     101

#define PROPERTY_ROBOT_EJECTCAM           0
#define PROPERTY_ROBOT_EJECTTRAJ          4
#define PROPSIZE_ROBOT                    8


//////////////Definition of class "Bell"
#define CLASSID_BELL                      102

#define PROPSIZE_BELL                     0


//////////////Definition of class "Watch"
#define CLASSID_WATCH                     103

#define PROPSIZE_WATCH                    0


//////////////Definition of class "DaffyLevel09"
#define CLASSID_DAFFYLEVEL09              104

#define PROPERTY_DAFFYLEVEL09_ACTIVATIONBOX 0
#define PROPERTY_DAFFYLEVEL09_BOXDEGUIS   4
#define PROPERTY_DAFFYLEVEL09_CAMERATRAJ  8
#define PROPERTY_DAFFYLEVEL09_CINE        12
#define PROPERTY_DAFFYLEVEL09_CINEBOX     16
#define PROPERTY_DAFFYLEVEL09_CINEDEGUIS  20
#define PROPERTY_DAFFYLEVEL09_CINEDEGUISFLAG 24
#define PROPERTY_DAFFYLEVEL09_CINEFLAG    28
#define PROPERTY_DAFFYLEVEL09_CINESHEEPBOX 32
#define PROPERTY_DAFFYLEVEL09_CINETEXT    36
#define PROPERTY_DAFFYLEVEL09_CINETEXTDEGUIS 40
#define PROPERTY_DAFFYLEVEL09_TRAJ        44
#define PROPERTY_DAFFYLEVEL09_TRAJRET     48
#define PROPSIZE_DAFFYLEVEL09             52


//////////////Definition of class "CanonDummy"
#define CLASSID_CANONDUMMY                105

#define PROPSIZE_CANONDUMMY               0


//////////////Definition of class "MapLocation"
#define CLASSID_MAPLOCATION               106

#define PROPERTY_MAPLOCATION_BOX01        0
#define PROPERTY_MAPLOCATION_BOX01POSX    4
#define PROPERTY_MAPLOCATION_BOX01POSY    8
#define PROPERTY_MAPLOCATION_BOX02        12
#define PROPERTY_MAPLOCATION_BOX02POSX    16
#define PROPERTY_MAPLOCATION_BOX02POSY    20
#define PROPERTY_MAPLOCATION_BOX03        24
#define PROPERTY_MAPLOCATION_BOX03POSX    28
#define PROPERTY_MAPLOCATION_BOX03POSY    32
#define PROPERTY_MAPLOCATION_BOX04        36
#define PROPERTY_MAPLOCATION_BOX04POSX    40
#define PROPERTY_MAPLOCATION_BOX04POSY    44
#define PROPERTY_MAPLOCATION_BOX05        48
#define PROPERTY_MAPLOCATION_BOX05POSX    52
#define PROPERTY_MAPLOCATION_BOX05POSY    56
#define PROPERTY_MAPLOCATION_BOX06        60
#define PROPERTY_MAPLOCATION_BOX06POSX    64
#define PROPERTY_MAPLOCATION_BOX06POSY    68
#define PROPERTY_MAPLOCATION_BOX07        72
#define PROPERTY_MAPLOCATION_BOX07POSX    76
#define PROPERTY_MAPLOCATION_BOX07POSY    80
#define PROPERTY_MAPLOCATION_BOX08        84
#define PROPERTY_MAPLOCATION_BOX08POSX    88
#define PROPERTY_MAPLOCATION_BOX08POSY    92
#define PROPERTY_MAPLOCATION_BOX09        96
#define PROPERTY_MAPLOCATION_BOX09POSX    100
#define PROPERTY_MAPLOCATION_BOX09POSY    104
#define PROPERTY_MAPLOCATION_BOX10        108
#define PROPERTY_MAPLOCATION_BOX10POSX    112
#define PROPERTY_MAPLOCATION_BOX10POSY    116
#define PROPERTY_MAPLOCATION_BOX11        120
#define PROPERTY_MAPLOCATION_BOX11POSX    124
#define PROPERTY_MAPLOCATION_BOX11POSY    128
#define PROPERTY_MAPLOCATION_BOX12        132
#define PROPERTY_MAPLOCATION_BOX12POSX    136
#define PROPERTY_MAPLOCATION_BOX12POSY    140
#define PROPERTY_MAPLOCATION_BOX13        144
#define PROPERTY_MAPLOCATION_BOX13POSX    148
#define PROPERTY_MAPLOCATION_BOX13POSY    152
#define PROPERTY_MAPLOCATION_BOX14        156
#define PROPERTY_MAPLOCATION_BOX14POSX    160
#define PROPERTY_MAPLOCATION_BOX14POSY    164
#define PROPERTY_MAPLOCATION_BOX15        168
#define PROPERTY_MAPLOCATION_BOX15POSX    172
#define PROPERTY_MAPLOCATION_BOX15POSY    176
#define PROPSIZE_MAPLOCATION              180


//////////////Definition of class "Bees"
#define CLASSID_BEES                      107

#define PROPERTY_BEES_BOXDETECTWOLF       0
#define PROPERTY_BEES_BOXFLY              4
#define PROPERTY_BEES_FIRSTHIVE           8
#define PROPERTY_BEES_MOTHERHIVE          12
#define PROPERTY_BEES_SECONDHIVE          16
#define PROPSIZE_BEES                     20


//////////////Definition of class "HoneyPot"
#define CLASSID_HONEYPOT                  108

#define PROPERTY_HONEYPOT_HIVEMOTHER      0
#define PROPSIZE_HONEYPOT                 4


//////////////Definition of class "CrocodileLevel09"
#define CLASSID_CROCODILELEVEL09          109

#define PROPERTY_CROCODILELEVEL09_ACTIVATIONBOX 0
#define PROPERTY_CROCODILELEVEL09_TRAJ    4
#define PROPERTY_CROCODILELEVEL09_WALK    8
#define PROPSIZE_CROCODILELEVEL09         12


//////////////Definition of class "Diamond"
#define CLASSID_DIAMOND                   110

#define PROPERTY_DIAMOND_BOXTELEPORT      0
#define PROPERTY_DIAMOND_TRAJ             4
#define PROPERTY_DIAMOND_ZONE             8
#define PROPSIZE_DIAMOND                  12


//////////////Definition of class "Wheel"
#define CLASSID_WHEEL                     111

#define PROPERTY_WHEEL_LIFT0              0
#define PROPERTY_WHEEL_LIFT1              4
#define PROPERTY_WHEEL_LIFT2              8
#define PROPERTY_WHEEL_LIFT3              12
#define PROPERTY_WHEEL_MOBIL              16
#define PROPERTY_WHEEL_RAISINGTIME        20
#define PROPERTY_WHEEL_SWITCHANGLE        24
#define PROPERTY_WHEEL_TRANSLATION        28
#define PROPSIZE_WHEEL                    32


//////////////Definition of class "WheelDummy"
#define CLASSID_WHEELDUMMY                112

#define PROPSIZE_WHEELDUMMY               0


//////////////Definition of class "Gossamer_Boss"
#define CLASSID_GOSSAMER_BOSS             113

#define PROPERTY_GOSSAMER_BOSS_BRIDGECAMERA 0
#define PROPERTY_GOSSAMER_BOSS_LIGHTBOX1  4
#define PROPERTY_GOSSAMER_BOSS_LIGHTBOX2  8
#define PROPERTY_GOSSAMER_BOSS_LIGHTBOX3  12
#define PROPERTY_GOSSAMER_BOSS_MOVEMENTBOX 16
#define PROPERTY_GOSSAMER_BOSS_POINTLIST  20
#define PROPERTY_GOSSAMER_BOSS_TIMER1     24
#define PROPERTY_GOSSAMER_BOSS_TIMER2     28
#define PROPERTY_GOSSAMER_BOSS_TIMER3     32
#define PROPSIZE_GOSSAMER_BOSS            36


//////////////Definition of class "SuperButton"
#define CLASSID_SUPERBUTTON               114

#define PROPERTY_SUPERBUTTON_NOT          0
#define PROPERTY_SUPERBUTTON_OUT          4
#define PROPSIZE_SUPERBUTTON              8


//////////////Definition of class "RollingCarpet"
#define CLASSID_ROLLINGCARPET             115

#define PROPERTY_ROLLINGCARPET_CAMERA     0
#define PROPERTY_ROLLINGCARPET_MOVING     4
#define PROPERTY_ROLLINGCARPET_RATIO      8
#define PROPERTY_ROLLINGCARPET_TARGET     12
#define PROPERTY_ROLLINGCARPET_TARGET2    16
#define PROPERTY_ROLLINGCARPET_TARGET3    20
#define PROPERTY_ROLLINGCARPET_TARGET4    24
#define PROPERTY_ROLLINGCARPET_TARGET5    28
#define PROPSIZE_ROLLINGCARPET            32


//////////////Definition of class "Hive"
#define CLASSID_HIVE                      116

#define PROPERTY_HIVE_CAMERA              0
#define PROPERTY_HIVE_MOTHER              4
#define PROPERTY_HIVE_TIME                8
#define PROPSIZE_HIVE                     12


//////////////Definition of class "Piranhas"
#define CLASSID_PIRANHAS                  117

#define PROPSIZE_PIRANHAS                 0


//////////////Definition of class "RCarpetMobile"
#define CLASSID_RCARPETMOBILE             118

#define PROPERTY_RCARPETMOBILE_SPEEDRATIO 0
#define PROPERTY_RCARPETMOBILE_TRAJECTORY 4
#define PROPSIZE_RCARPETMOBILE            8


//////////////Definition of class "CrumblyGround"
#define CLASSID_CRUMBLYGROUND             119

#define PROPSIZE_CRUMBLYGROUND            0


//////////////Definition of class "Ghost"
#define CLASSID_GHOST                     120

#define PROPERTY_GHOST_ACTIVATIONBOX      0
#define PROPERTY_GHOST_MASTER             4
#define PROPSIZE_GHOST                    8


//////////////Definition of class "SaladRod"
#define CLASSID_SALADROD                  121

#define PROPSIZE_SALADROD                 0


//////////////Definition of class "CrocodileLevel11"
#define CLASSID_CROCODILELEVEL11          122

#define PROPERTY_CROCODILELEVEL11_ACTIVATIONBOX 0
#define PROPERTY_CROCODILELEVEL11_BOXES   4
#define PROPERTY_CROCODILELEVEL11_CAMERA  8
#define PROPERTY_CROCODILELEVEL11_CINE    12
#define PROPERTY_CROCODILELEVEL11_CINEBOX 16
#define PROPERTY_CROCODILELEVEL11_CINEFLAG 20
#define PROPERTY_CROCODILELEVEL11_CINESHEEPBOX 24
#define PROPERTY_CROCODILELEVEL11_CINETEXT 28
#define PROPERTY_CROCODILELEVEL11_DAFFY   32
#define PROPERTY_CROCODILELEVEL11_REMAINDEADATRESET 36
#define PROPSIZE_CROCODILELEVEL11         40


//////////////Definition of class "Monolithe"
#define CLASSID_MONOLITHE                 123

#define PROPERTY_MONOLITHE_CAMERA         0
#define PROPERTY_MONOLITHE_SHEEPBOX       4
#define PROPSIZE_MONOLITHE                8


//////////////Definition of class "LightSpot"
#define CLASSID_LIGHTSPOT                 124

#define PROPERTY_LIGHTSPOT_AUTHORIZEDBOX  0
#define PROPERTY_LIGHTSPOT_COLOR          4
#define PROPERTY_LIGHTSPOT_NBHEIGHTSEGS   8
#define PROPERTY_LIGHTSPOT_NUMSIDES       12
#define PROPERTY_LIGHTSPOT_RADIUS         16
#define PROPERTY_LIGHTSPOT_TRAJECTORY     20
#define PROPSIZE_LIGHTSPOT                24


//////////////Definition of class "GhostCostume"
#define CLASSID_GHOSTCOSTUME              125

#define PROPSIZE_GHOSTCOSTUME             0


//////////////Definition of class "Jail"
#define CLASSID_JAIL                      126

#define PROPERTY_JAIL_BUTTONHIGH          0
#define PROPERTY_JAIL_BUTTONLOW           4
#define PROPERTY_JAIL_BUTTONMIDDLE        8
#define PROPERTY_JAIL_HEIGHT              12
#define PROPERTY_JAIL_TRAJECTORY          16
#define PROPSIZE_JAIL                     20


//////////////Definition of class "DancingGhost"
#define CLASSID_DANCINGGHOST              127

#define PROPERTY_DANCINGGHOST_CHATBOX     0
#define PROPERTY_DANCINGGHOST_PLAYTAMBOURINE 4
#define PROPERTY_DANCINGGHOST_TRAJECTORY  8
#define PROPSIZE_DANCINGGHOST             12


//////////////Definition of class "Battery"
#define CLASSID_BATTERY                   128

#define PROPERTY_BATTERY_ACTIVATIONBOX    0
#define PROPERTY_BATTERY_MASTER           4
#define PROPSIZE_BATTERY                  8


//////////////Definition of class "Key"
#define CLASSID_KEY                       129

#define PROPSIZE_KEY                      0


//////////////Definition of class "PrayingGhost"
#define CLASSID_PRAYINGGHOST              130

#define PROPERTY_PRAYINGGHOST_CAMERARESTRICTION1 0
#define PROPERTY_PRAYINGGHOST_CAMERARESTRICTION2 4
#define PROPERTY_PRAYINGGHOST_CAMERARESTRICTION3 8
#define PROPERTY_PRAYINGGHOST_CHECKPOINT  12
#define PROPERTY_PRAYINGGHOST_CHECKPOINTJAIL 16
#define PROPERTY_PRAYINGGHOST_FALLINGGATE 20
#define PROPERTY_PRAYINGGHOST_FALLINGGATEDETEC 24
#define PROPERTY_PRAYINGGHOST_SHEEP       28
#define PROPERTY_PRAYINGGHOST_SHEEPBOX    32
#define PROPERTY_PRAYINGGHOST_STARTBOX    36
#define PROPERTY_PRAYINGGHOST_TIMEORANGE  40
#define PROPERTY_PRAYINGGHOST_TRAJECTORY  44
#define PROPERTY_PRAYINGGHOST_WOLFINVISIBLE1 48
#define PROPERTY_PRAYINGGHOST_WOLFNOTVISIBLEMONO 52
#define PROPSIZE_PRAYINGGHOST             56


//////////////Definition of class "Hoover"
#define CLASSID_HOOVER                    131

#define PROPERTY_HOOVER_ACTIVATIONBOX     0
#define PROPSIZE_HOOVER                   4


//////////////Definition of class "InflatableSheep"
#define CLASSID_INFLATABLESHEEP           132

#define PROPSIZE_INFLATABLESHEEP          0


//////////////Definition of class "TrafficJams"
#define CLASSID_TRAFFICJAMS               133

#define PROPERTY_TRAFFICJAMS_ARRIVINGTIME 0
#define PROPERTY_TRAFFICJAMS_BOXSTATION   4
#define PROPERTY_TRAFFICJAMS_BREAKTIME    8
#define PROPERTY_TRAFFICJAMS_NEXTJAMS     12
#define PROPERTY_TRAFFICJAMS_TRAINSTATION 16
#define PROPSIZE_TRAFFICJAMS              20


//////////////Definition of class "Chronometer"
#define CLASSID_CHRONOMETER               134

#define PROPSIZE_CHRONOMETER              0


//////////////Definition of class "Train"
#define CLASSID_TRAIN                     135

#define PROPERTY_TRAIN_DOCKA              0
#define PROPERTY_TRAIN_DOCKB              4
#define PROPERTY_TRAIN_FIRST              8
#define PROPERTY_TRAIN_JUMPINSHEEPBOX     12
#define PROPERTY_TRAIN_OFFTRAINBOX        16
#define PROPERTY_TRAIN_SAFERECALBOX       20
#define PROPSIZE_TRAIN                    24


//////////////Definition of class "TrainStation"
#define CLASSID_TRAINSTATION              136

#define PROPERTY_TRAINSTATION_BOX         0
#define PROPERTY_TRAINSTATION_CAM         4
#define PROPERTY_TRAINSTATION_NEXT        8
#define PROPERTY_TRAINSTATION_SPEEDPERCENT 12
#define PROPERTY_TRAINSTATION_TRAJ        16
#define PROPERTY_TRAINSTATION_WAIT        20
#define PROPSIZE_TRAINSTATION             24


//////////////Definition of class "AmbientSoundManager"
#define CLASSID_AMBIENTSOUNDMANAGER       137

#define PROPERTY_AMBIENTSOUNDMANAGER_FLAGS 0
#define PROPERTY_AMBIENTSOUNDMANAGER_MAXDIST 4
#define PROPERTY_AMBIENTSOUNDMANAGER_REPEATTIMEMAXMS 8
#define PROPERTY_AMBIENTSOUNDMANAGER_REPEATTIMEMINMS 12
#define PROPERTY_AMBIENTSOUNDMANAGER_SOUNDBOX 16
#define PROPERTY_AMBIENTSOUNDMANAGER_SOUNDID 20
#define PROPERTY_AMBIENTSOUNDMANAGER_SOUNDMAXVOLBOX 24
#define PROPERTY_AMBIENTSOUNDMANAGER_VOLUME 28
#define PROPSIZE_AMBIENTSOUNDMANAGER      32


//////////////Definition of class "GhostHalo"
#define CLASSID_GHOSTHALO                 138

#define PROPSIZE_GHOSTHALO                0


//////////////Definition of class "BipbipLevel14"
#define CLASSID_BIPBIPLEVEL14             139

#define PROPERTY_BIPBIPLEVEL14_BOXSTOPBIPBIP 0
#define PROPERTY_BIPBIPLEVEL14_GOTOTRAJECTORY 4
#define PROPERTY_BIPBIPLEVEL14_RETURNTRAJECTORY 8
#define PROPERTY_BIPBIPLEVEL14_TIMEWAIT   12
#define PROPERTY_BIPBIPLEVEL14_TRAINSTATION 16
#define PROPSIZE_BIPBIPLEVEL14            20


//////////////Definition of class "FallingGate2"
#define CLASSID_FALLINGGATE2              140

#define PROPERTY_FALLINGGATE2_2BUTTON     0
#define PROPERTY_FALLINGGATE2_CAMERA      4
#define PROPERTY_FALLINGGATE2_CLOSED      8
#define PROPERTY_FALLINGGATE2_FALLINGTIME 12
#define PROPERTY_FALLINGGATE2_ONLYONEACTIVATION 16
#define PROPSIZE_FALLINGGATE2             20


//////////////Definition of class "GoldenCoins"
#define CLASSID_GOLDENCOINS               141

#define PROPSIZE_GOLDENCOINS              0


//////////////Definition of class "Sam_Pirate"
#define CLASSID_SAM_PIRATE                142

#define PROPERTY_SAM_PIRATE_BOX_FORBIDDEN 0
#define PROPERTY_SAM_PIRATE_BOX_NEAR_JAIL 4
#define PROPERTY_SAM_PIRATE_BRIDGE_BOX    8
#define PROPERTY_SAM_PIRATE_JAIL_BOX      12
#define PROPERTY_SAM_PIRATE_NBER_OF_COIN  16
#define PROPERTY_SAM_PIRATE_TEXT_IN_BOAT1 20
#define PROPERTY_SAM_PIRATE_TEXT_IN_BOAT2 24
#define PROPERTY_SAM_PIRATE_TEXT_IN_JAIL  28
#define PROPERTY_SAM_PIRATE_TRAJ_BOAT     32
#define PROPSIZE_SAM_PIRATE               36


//////////////Definition of class "FloatingBox"
#define CLASSID_FLOATINGBOX               143

#define PROPERTY_FLOATINGBOX_CONTAINS     0
#define PROPSIZE_FLOATINGBOX              4


//////////////Definition of class "InstantHoover"
#define CLASSID_INSTANTHOOVER             144

#define PROPERTY_INSTANTHOOVER_ACTIVEBOX  0
#define PROPERTY_INSTANTHOOVER_BOXPOSITION 4
#define PROPERTY_INSTANTHOOVER_HORRANGE   8
#define PROPERTY_INSTANTHOOVER_OPENTIME   12
#define PROPERTY_INSTANTHOOVER_VERTRANGE  16
#define PROPSIZE_INSTANTHOOVER            20


//////////////Definition of class "InstantMartian"
#define CLASSID_INSTANTMARTIAN            145

#define PROPERTY_INSTANTMARTIAN_BOX       0
#define PROPERTY_INSTANTMARTIAN_BOX2      4
#define PROPERTY_INSTANTMARTIAN_BOX3      8
#define PROPERTY_INSTANTMARTIAN_BOX4      12
#define PROPERTY_INSTANTMARTIAN_BOX5      16
#define PROPERTY_INSTANTMARTIAN_CHECKPOINTBOX 20
#define PROPERTY_INSTANTMARTIAN_COLFORTRAJ 24
#define PROPERTY_INSTANTMARTIAN_DETECTBOX 28
#define PROPERTY_INSTANTMARTIAN_MARTIENBEHAVIOR 32
#define PROPERTY_INSTANTMARTIAN_TRAJECTORY 36
#define PROPERTY_INSTANTMARTIAN_TRAJECTORY2 40
#define PROPSIZE_INSTANTMARTIAN           44


//////////////Definition of class "CanonSheep"
#define CLASSID_CANONSHEEP                146

#define PROPERTY_CANONSHEEP_ACTIVATIONBOX 0
#define PROPERTY_CANONSHEEP_CINE          4
#define PROPERTY_CANONSHEEP_CINEFLAG      8
#define PROPERTY_CANONSHEEP_CINETEXT      12
#define PROPERTY_CANONSHEEP_DETECTBOX     16
#define PROPERTY_CANONSHEEP_HORZLIMIT     20
#define PROPERTY_CANONSHEEP_LAUNCHPOINT1  24
#define PROPERTY_CANONSHEEP_LAUNCHPOINT2  28
#define PROPERTY_CANONSHEEP_LAUNCHPOINT3  32
#define PROPERTY_CANONSHEEP_LOADBOX       36
#define PROPERTY_CANONSHEEP_VERTLIMIT     40
#define PROPERTY_CANONSHEEP_VOIDCAMERA    44
#define PROPSIZE_CANONSHEEP               48


//////////////Definition of class "CannonBall2"
#define CLASSID_CANNONBALL2               147

#define PROPSIZE_CANNONBALL2              0


//////////////Definition of class "SceneSheepPanel"
#define CLASSID_SCENESHEEPPANEL           148

#define PROPERTY_SCENESHEEPPANEL_ID_CAMERA 0
#define PROPERTY_SCENESHEEPPANEL_ID_CINE  4
#define PROPERTY_SCENESHEEPPANEL_ID_SHEEPBOX 8
#define PROPSIZE_SCENESHEEPPANEL          12


//////////////Definition of class "LazerRobot"
#define CLASSID_LAZERROBOT                149

#define PROPERTY_LAZERROBOT_SPEED         0
#define PROPERTY_LAZERROBOT_TRAJ          4
#define PROPSIZE_LAZERROBOT               8


//////////////Definition of class "Laser"
#define CLASSID_LASER                     150

#define PROPERTY_LASER_ACTIVATIONDELAY    0
#define PROPERTY_LASER_BOX                4
#define PROPERTY_LASER_INACTIVE           8
#define PROPERTY_LASER_TYPE               12
#define PROPSIZE_LASER                    16


//////////////Definition of class "Case"
#define CLASSID_CASE                      151

#define PROPSIZE_CASE                     0


//////////////Definition of class "Scene_Wheel"
#define CLASSID_SCENE_WHEEL               152

#define PROPSIZE_SCENE_WHEEL              0


//////////////Definition of class "Scene_Arrow"
#define CLASSID_SCENE_ARROW               153

#define PROPSIZE_SCENE_ARROW              0


//////////////Definition of class "Scene_Screen"
#define CLASSID_SCENE_SCREEN              154

#define PROPSIZE_SCENE_SCREEN             0


//////////////Definition of class "DaffyScene"
#define CLASSID_DAFFYSCENE                155

#define PROPERTY_DAFFYSCENE_CAMCOUNTER    0
#define PROPERTY_DAFFYSCENE_CAMLEVEL      4
#define PROPERTY_DAFFYSCENE_CAMSAVE       8
#define PROPERTY_DAFFYSCENE_CAMSPEAK1     12
#define PROPERTY_DAFFYSCENE_CAMSPEAK2     16
#define PROPERTY_DAFFYSCENE_CAMSPEAK3     20
#define PROPERTY_DAFFYSCENE_CAMSPEAK4     24
#define PROPERTY_DAFFYSCENE_CAMSPEAK5     28
#define PROPERTY_DAFFYSCENE_CAMTIMECLOCK  32
#define PROPERTY_DAFFYSCENE_CINE          36
#define PROPERTY_DAFFYSCENE_CINEFLAG      40
#define PROPERTY_DAFFYSCENE_CINETEXT      44
#define PROPERTY_DAFFYSCENE_CROWD         48
#define PROPERTY_DAFFYSCENE_MAINCAMERA    52
#define PROPERTY_DAFFYSCENE_TEXTCOUNTER   56
#define PROPERTY_DAFFYSCENE_TEXTFAILINFIRSTLVL 60
#define PROPERTY_DAFFYSCENE_TEXTLEVEL     64
#define PROPERTY_DAFFYSCENE_TEXTNEWCONTESTANT 68
#define PROPERTY_DAFFYSCENE_TEXTNOTIMEKEEPER 72
#define PROPERTY_DAFFYSCENE_TEXTPHONE     76
#define PROPERTY_DAFFYSCENE_TEXTQUITTER   80
#define PROPERTY_DAFFYSCENE_TEXTSAVE      84
#define PROPERTY_DAFFYSCENE_TEXTSUPPORT   88
#define PROPERTY_DAFFYSCENE_TEXTTIMECLOCK 92
#define PROPERTY_DAFFYSCENE_TEXTVICTORY1  96
#define PROPERTY_DAFFYSCENE_TEXTVICTORY2  100
#define PROPERTY_DAFFYSCENE_TEXTVICTORY3  104
#define PROPERTY_DAFFYSCENE_TEXTVICTORY4  108
#define PROPERTY_DAFFYSCENE_TEXTVICTORY5  112
#define PROPSIZE_DAFFYSCENE               116


//////////////Definition of class "AutomaticDoor"
#define CLASSID_AUTOMATICDOOR             156

#define PROPERTY_AUTOMATICDOOR_SENSIBLEBOXES 0
#define PROPSIZE_AUTOMATICDOOR            4


//////////////Definition of class "Resizer"
#define CLASSID_RESIZER                   157

#define PROPERTY_RESIZER__EXIT            0
#define PROPERTY_RESIZER__MAXIMIZE        4
#define PROPERTY_RESIZER_ACTIVATIONBOX    8
#define PROPERTY_RESIZER_EXIT             12
#define PROPSIZE_RESIZER                  16


//////////////Definition of class "Bat"
#define CLASSID_BAT                       158

#define PROPSIZE_BAT                      0


//////////////Definition of class "Firefly"
#define CLASSID_FIREFLY                   159

#define PROPSIZE_FIREFLY                  0


//////////////Definition of class "Bird"
#define CLASSID_BIRD                      160

#define PROPERTY_BIRD_APPEARBOX           0
#define PROPSIZE_BIRD                     4


//////////////Definition of class "Butterfly"
#define CLASSID_BUTTERFLY                 161

#define PROPERTY_BUTTERFLY_4BUTTERFLY     0
#define PROPERTY_BUTTERFLY_APPEARBOX      4
#define PROPSIZE_BUTTERFLY                8


//////////////Definition of class "Fish"
#define CLASSID_FISH                      162

#define PROPERTY_FISH_DISAPPEAR_DIST      0
#define PROPSIZE_FISH                     4


//////////////Definition of class "Pipe2"
#define CLASSID_PIPE2                     163

#define PROPERTY_PIPE2_BOXACT1            0
#define PROPERTY_PIPE2_BOXACTI2           4
#define PROPSIZE_PIPE2                    8


//////////////Definition of class "Lava"
#define CLASSID_LAVA                      164

#define PROPERTY_LAVA_RANGE               0
#define PROPSIZE_LAVA                     4


//////////////Definition of class "SignPostAnimated"
#define CLASSID_SIGNPOSTANIMATED          165

#define PROPERTY_SIGNPOSTANIMATED_DISTANCE 0
#define PROPERTY_SIGNPOSTANIMATED_HIDDEN  4
#define PROPERTY_SIGNPOSTANIMATED_INDEXTEXT 8
#define PROPSIZE_SIGNPOSTANIMATED         12


//////////////Definition of class "Volcano"
#define CLASSID_VOLCANO                   166

#define PROPERTY_VOLCANO_TRAJ1            0
#define PROPERTY_VOLCANO_UTURN            4
#define PROPERTY_VOLCANO_VERTICAL         8
#define PROPSIZE_VOLCANO                  12


//////////////Definition of class "DancingGhostManager"
#define CLASSID_DANCINGGHOSTMANAGER       167

#define PROPERTY_DANCINGGHOSTMANAGER_BOX_COSTUM 0
#define PROPERTY_DANCINGGHOSTMANAGER_BOX_EXT 4
#define PROPERTY_DANCINGGHOSTMANAGER_BOX_INT 8
#define PROPERTY_DANCINGGHOSTMANAGER_BOX_REMOVE 12
#define PROPERTY_DANCINGGHOSTMANAGER_BOX_SAF 16
#define PROPERTY_DANCINGGHOSTMANAGER_BOXSTEP1 20
#define PROPERTY_DANCINGGHOSTMANAGER_BOXSTEP2 24
#define PROPERTY_DANCINGGHOSTMANAGER_BOXSTEP3 28
#define PROPERTY_DANCINGGHOSTMANAGER_BOXSTEP4 32
#define PROPERTY_DANCINGGHOSTMANAGER_CINE 36
#define PROPERTY_DANCINGGHOSTMANAGER_CINEBOX 40
#define PROPERTY_DANCINGGHOSTMANAGER_CINEFLAGS 44
#define PROPERTY_DANCINGGHOSTMANAGER_CINETEXT 48
#define PROPERTY_DANCINGGHOSTMANAGER_CONGRATULID 52
#define PROPERTY_DANCINGGHOSTMANAGER_DANCECAM1 56
#define PROPERTY_DANCINGGHOSTMANAGER_DANCECAM2 60
#define PROPERTY_DANCINGGHOSTMANAGER_DANCECAM3 64
#define PROPERTY_DANCINGGHOSTMANAGER_DANCECAM4 68
#define PROPERTY_DANCINGGHOSTMANAGER_EXPLAINBUTID 72
#define PROPERTY_DANCINGGHOSTMANAGER_EXPLAINBUTSYNCID 76
#define PROPERTY_DANCINGGHOSTMANAGER_EXPLAINPATHID 80
#define PROPERTY_DANCINGGHOSTMANAGER_EXPLAINSYNCID 84
#define PROPERTY_DANCINGGHOSTMANAGER_SEQID 88
#define PROPERTY_DANCINGGHOSTMANAGER_STEPCLEAREDID 92
#define PROPSIZE_DANCINGGHOSTMANAGER      96


//////////////Definition of class "DoorsMaster"
#define CLASSID_DOORSMASTER               168

#define PROPSIZE_DOORSMASTER              0


//////////////Definition of class "DoorWorld"
#define CLASSID_DOORWORLD                 169

#define PROPERTY_DOORWORLD_CAMERAOPEN     0
#define PROPERTY_DOORWORLD_IDDOORLEVEL    4
#define PROPSIZE_DOORWORLD                8


//////////////Definition of class "DoorLevel"
#define CLASSID_DOORLEVEL                 170

#define PROPERTY_DOORLEVEL_IDBOXBACK      0
#define PROPERTY_DOORLEVEL_LEVELNUMBER    4
#define PROPSIZE_DOORLEVEL                8


//////////////Definition of class "FireBall"
#define CLASSID_FIREBALL                  171

#define PROPSIZE_FIREBALL                 0


//////////////Definition of class "Twig"
#define CLASSID_TWIG                      172

#define PROPERTY_TWIG_DISAPPEAR_DIST      0
#define PROPSIZE_TWIG                     4


//////////////Definition of class "GeyserManger"
#define CLASSID_GEYSERMANGER              173

#define PROPERTY_GEYSERMANGER_BOXDETECT   0
#define PROPERTY_GEYSERMANGER_GEYSER01    4
#define PROPERTY_GEYSERMANGER_GEYSER02    8
#define PROPERTY_GEYSERMANGER_GEYSER03    12
#define PROPERTY_GEYSERMANGER_GEYSER04    16
#define PROPERTY_GEYSERMANGER_GEYSER05    20
#define PROPERTY_GEYSERMANGER_GEYSER06    24
#define PROPERTY_GEYSERMANGER_GEYSER07    28
#define PROPERTY_GEYSERMANGER_GEYSER08    32
#define PROPERTY_GEYSERMANGER_GEYSER09    36
#define PROPERTY_GEYSERMANGER_GEYSER10    40
#define PROPERTY_GEYSERMANGER_GEYSER11    44
#define PROPERTY_GEYSERMANGER_GEYSER12    48
#define PROPERTY_GEYSERMANGER_GEYSER13    52
#define PROPERTY_GEYSERMANGER_GEYSER14    56
#define PROPERTY_GEYSERMANGER_GEYSER15    60
#define PROPERTY_GEYSERMANGER_GEYSER16    64
#define PROPSIZE_GEYSERMANGER             68


//////////////Definition of class "SignTips"
#define CLASSID_SIGNTIPS                  174

#define PROPERTY_SIGNTIPS_CAMERA          0
#define PROPERTY_SIGNTIPS_CHECKPOINT      4
#define PROPERTY_SIGNTIPS_DIST            8
#define PROPERTY_SIGNTIPS_INDEXTEXT       12
#define PROPERTY_SIGNTIPS_NBREBIRTH       16
#define PROPERTY_SIGNTIPS_TRAJBOXES       20
#define PROPSIZE_SIGNTIPS                 24


//////////////Definition of class "MirrorManager"
#define CLASSID_MIRRORMANAGER             175

#define PROPERTY_MIRRORMANAGER_COLORINTENSITY 0
#define PROPERTY_MIRRORMANAGER_GROUNDALTITUDE 4
#define PROPERTY_MIRRORMANAGER_ID_OBJECT01 8
#define PROPERTY_MIRRORMANAGER_ID_OBJECT02 12
#define PROPERTY_MIRRORMANAGER_ID_OBJECT03 16
#define PROPERTY_MIRRORMANAGER_ID_OBJECT04 20
#define PROPERTY_MIRRORMANAGER_ID_OBJECT05 24
#define PROPERTY_MIRRORMANAGER_ID_OBJECT06 28
#define PROPERTY_MIRRORMANAGER_ID_OBJECT07 32
#define PROPERTY_MIRRORMANAGER_ID_OBJECT08 36
#define PROPERTY_MIRRORMANAGER_IDBOX      40
#define PROPERTY_MIRRORMANAGER_MIRRORCOLOR 44
#define PROPSIZE_MIRRORMANAGER            48


//////////////Definition of class "CreditsManager"
#define CLASSID_CREDITSMANAGER            176

#define PROPERTY_CREDITSMANAGER_COLOR     0
#define PROPERTY_CREDITSMANAGER_TEXTJUST  4
#define PROPERTY_CREDITSMANAGER_TEXTNUM   8
#define PROPERTY_CREDITSMANAGER_TIME_APP  12
#define PROPERTY_CREDITSMANAGER_TIME_DIS  16
#define PROPSIZE_CREDITSMANAGER           20


//////////////Definition of class "WaterMine"
#define CLASSID_WATERMINE                 177

#define PROPSIZE_WATERMINE                0


//////////////Definition of class "Rook"
#define CLASSID_ROOK                      178

#define PROPERTY_ROOK_BOXDETECT           0
#define PROPERTY_ROOK_CANNON              4
#define PROPERTY_ROOK_CANNONBALL          8
#define PROPERTY_ROOK_DISTDETECT          12
#define PROPERTY_ROOK_SPEED               16
#define PROPERTY_ROOK_TRAJECTORY          20
#define PROPSIZE_ROOK                     24


//////////////Definition of class "SfxCineManager"
#define CLASSID_SFXCINEMANAGER            179

#define PROPERTY_SFXCINEMANAGER_FINALSIZE 0
#define PROPERTY_SFXCINEMANAGER_LIFETIME  4
#define PROPERTY_SFXCINEMANAGER_MOVESPEED 8
#define PROPERTY_SFXCINEMANAGER_NBSFX     12
#define PROPERTY_SFXCINEMANAGER_POSX      16
#define PROPERTY_SFXCINEMANAGER_POSY      20
#define PROPERTY_SFXCINEMANAGER_POSZ      24
#define PROPERTY_SFXCINEMANAGER_SIZE      28
#define PROPERTY_SFXCINEMANAGER_TARGET    32
#define PROPERTY_SFXCINEMANAGER_TYPESFX   36
#define PROPSIZE_SFXCINEMANAGER           40


//////////////Definition of class "CineMatrixMode"
#define CLASSID_CINEMATRIXMODE            180

#define PROPERTY_CINEMATRIXMODE_BOX       0
#define PROPSIZE_CINEMATRIXMODE           4


//////////////Definition of class "CrumblyPlat"
#define CLASSID_CRUMBLYPLAT               181

#define PROPSIZE_CRUMBLYPLAT              0


//////////////Definition of class "GossamerOnde"
#define CLASSID_GOSSAMERONDE              182

#define PROPSIZE_GOSSAMERONDE             0


//////////////Definition of class "FacingCamera"
#define CLASSID_FACINGCAMERA              183

#define PROPSIZE_FACINGCAMERA             0


//////////////Definition of class "ObjectManager"
#define CLASSID_OBJECTMANAGER             184

#define PROPERTY_OBJECTMANAGER_ACTION     0
#define PROPERTY_OBJECTMANAGER_MANAGEINBOXES 4
#define PROPERTY_OBJECTMANAGER_OBJECT01   8
#define PROPERTY_OBJECTMANAGER_OBJECT02   12
#define PROPERTY_OBJECTMANAGER_OBJECT03   16
#define PROPERTY_OBJECTMANAGER_OBJECT04   20
#define PROPERTY_OBJECTMANAGER_OBJECT05   24
#define PROPERTY_OBJECTMANAGER_OBJECT06   28
#define PROPERTY_OBJECTMANAGER_OBJECT07   32
#define PROPERTY_OBJECTMANAGER_OBJECT08   36
#define PROPERTY_OBJECTMANAGER_OBJECT09   40
#define PROPERTY_OBJECTMANAGER_OBJECT10   44
#define PROPERTY_OBJECTMANAGER_OBJECT11   48
#define PROPERTY_OBJECTMANAGER_OBJECT12   52
#define PROPERTY_OBJECTMANAGER_OBJECT13   56
#define PROPERTY_OBJECTMANAGER_OBJECT14   60
#define PROPERTY_OBJECTMANAGER_OBJECT15   64
#define PROPERTY_OBJECTMANAGER_OBJECT16   68
#define PROPERTY_OBJECTMANAGER_OBJECT17   72
#define PROPERTY_OBJECTMANAGER_OBJECT18   76
#define PROPERTY_OBJECTMANAGER_OBJECT19   80
#define PROPERTY_OBJECTMANAGER_OBJECT20   84
#define PROPSIZE_OBJECTMANAGER            88


//////////////Definition of class "HiddenButton"
#define CLASSID_HIDDENBUTTON              185

#define PROPERTY_HIDDENBUTTON_TARGET      0
#define PROPERTY_HIDDENBUTTON_TARGET2     4
#define PROPERTY_HIDDENBUTTON_TYPE        8
#define PROPSIZE_HIDDENBUTTON             12


//////////////Definition of class "WaterGeyser"
#define CLASSID_WATERGEYSER               186

#define PROPERTY_WATERGEYSER_BOXDECTECT   0
#define PROPERTY_WATERGEYSER_GEYSEROUT    4
#define PROPERTY_WATERGEYSER_TIMEINHOLE   8
#define PROPSIZE_WATERGEYSER              12


//////////////Definition of class "DaffyWheel"
#define CLASSID_DAFFYWHEEL                187

#define PROPERTY_DAFFYWHEEL_IDCAMBEGIN    0
#define PROPERTY_DAFFYWHEEL_IDCAMERA      4
#define PROPSIZE_DAFFYWHEEL               8


//////////////Definition of class "Torch"
#define CLASSID_TORCH                     188

#define PROPSIZE_TORCH                    0


//////////////Definition of class "Sail"
#define CLASSID_SAIL                      189

#define PROPSIZE_SAIL                     0


//////////////Definition of class "BonusManager"
#define CLASSID_BONUSMANAGER              190

#define PROPERTY_BONUSMANAGER_IDCAMERA    0
#define PROPSIZE_BONUSMANAGER             4


//////////////Definition of class "Leaf"
#define CLASSID_LEAF                      191

#define PROPERTY_LEAF_RANGE               0
#define PROPSIZE_LEAF                     4


//////////////Definition of class "BlackHole"
#define CLASSID_BLACKHOLE                 192

#define PROPSIZE_BLACKHOLE                0


//////////////Definition of class "Marvin"
#define CLASSID_MARVIN                    193

#define PROPERTY_MARVIN_CINE              0
#define PROPERTY_MARVIN_CINEBOX           4
#define PROPERTY_MARVIN_CINEFLAGS         8
#define PROPERTY_MARVIN_CINETEXT          12
#define PROPERTY_MARVIN_MOCKERYID1        16
#define PROPERTY_MARVIN_MOCKERYID2        20
#define PROPERTY_MARVIN_SUCCESSID1        24
#define PROPERTY_MARVIN_SUCCESSID2        28
#define PROPSIZE_MARVIN                   32


//////////////Definition of class "InstantSocket"
#define CLASSID_INSTANTSOCKET             194

#define PROPSIZE_INSTANTSOCKET            0


//////////////Definition of class "Crowd"
#define CLASSID_CROWD                     195

#define PROPSIZE_CROWD                    0


//////////////Definition of class "CameraManager2"
#define CLASSID_CAMERAMANAGER2            196

#define PROPERTY_CAMERAMANAGER2_BOXES     0
#define PROPERTY_CAMERAMANAGER2_CAMERA    4
#define PROPERTY_CAMERAMANAGER2_FLAGS     8
#define PROPSIZE_CAMERAMANAGER2           12



#endif
